(()=>{
const RADAR_SECTION=['radar','◈','Radar','Radar de decisiones','Cara a cara por media, Power, minutos, eficiencia, forma y comunidad.'];
let insertAt=sections.findIndex(s=>s[0]==='comparador');if(!sections.some(s=>s[0]==='radar'))sections.splice(Math.max(0,insertAt),0,RADAR_SECTION);
const R_PRESETS=[
  {id:'ld',label:'Lateral derecho',a:'Dumfries',b:'Trent Alexander-Arnold',note:'Explosividad y presencia física frente a construcción y creatividad interior.'},
  {id:'central',label:'Central',a:'Konaté',b:'Rüdiger',note:'Continuidad y muestra acumulada frente a experiencia y rendimiento por minuto.'},
  {id:'li',label:'Lateral izquierdo',a:'Álvaro Carreras',b:'Cucurella',note:'Eficiencia de muestra corta frente a continuidad y peso de minutos.'},
  {id:'banda',label:'Banda derecha',a:'Diomande',b:'Brahim Díaz',note:'Amplitud y profundidad frente a asociación y juego interior.'}
];
let radarA='Dumfries',radarB='Trent Alexander-Arnold',radarCommunity=window.RMCommunityData||null,radarPolls=null,radarLoading=false;
function season(){return window.RMSeasonData}
function rEsc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function rPlayer(name){return players.find(p=>p.name===name)}
function rMetric(name){const p=rPlayer(name);return p?metricFor(p):null}
function rRating(name){return currentRating(rMetric(name))}
function rPower(name){const m=rMetric(name),rating=rRating(name);if(!m||rating===null)return null;const sample=Math.min(m.minutes,450)/450;return rating*(.75+.25*sample)}
function rRecent(name){return season()?.recentRating(name,3)||null}
function backendAvailable(){try{return typeof communityBackendAvailable==='function'?communityBackendAvailable():/^https?:$/.test(location.protocol)&&!location.hostname.endsWith('github.io')}catch{return false}}
function rGlobalCommunity(name){if(!radarCommunity?.slotShares)return null;let best=null;for(const rows of Object.values(radarCommunity.slotShares))for(const row of rows||[])if((season()?.canonical(row.name)||row.name)===(season()?.canonical(name)||name)){const value=typeof row.globalPercentage==='number'?row.globalPercentage:row.percentage;if(best===null||value>best)best=value}return best}
function rDirectPoll(a,b){const poll=(radarPolls?.polls||[]).find(p=>{const labels=(p.options||[]).map(o=>season()?.canonical(o.label)||o.label),ca=season()?.canonical(a)||a,cb=season()?.canonical(b)||b;return labels.includes(ca)&&labels.includes(cb)});if(!poll||!poll.total)return null;const find=name=>poll.options.find(o=>(season()?.canonical(o.label)||o.label)===(season()?.canonical(name)||name));const A=find(a),B=find(b);return A&&B?{a:A.percentage,b:B.percentage,total:poll.total,source:'Encuesta directa'}:null}
function rCommunityPair(a,b){const direct=rDirectPoll(a,b);if(direct)return direct;const A=rGlobalCommunity(a),B=rGlobalCommunity(b);if(A===null&&B===null)return null;return {a:A??0,b:B??0,total:radarCommunity?.totalPredictions||0,source:'XI de la comunidad'}}
function cmpHigher(a,b){if(a===null||a===undefined||b===null||b===undefined)return null;if(Math.abs(a-b)<.0001)return 0;return a>b?1:-1}
function cmpLower(a,b){if(a===null||a===undefined||b===null||b===undefined)return null;if(Math.abs(a-b)<.0001)return 0;return a<b?1:-1}
function diff(a,b,digits=2){if(a===null||a===undefined||b===null||b===undefined)return null;return Math.abs(a-b).toFixed(digits)}
function whyText(id,winner,a,b,aName,bName){if(winner===null)return id==='community'&&!backendAvailable()?'Comunidad en vivo no disponible en GitHub Pages.':'Falta un dato comparable.';if(winner===0)return 'Los dos están igualados en este criterio.';const lead=winner===1?aName:bName;switch(id){case'rating':return `${lead} tiene ${diff(a,b)} puntos más de media.`;case'power':return `${lead} tiene ${diff(a,b)} puntos más de Power RM.`;case'minutes':return `${lead} acumula ${Math.abs((a||0)-(b||0))} minutos más.`;case'eff':return `${lead} necesita ${diff(a,b)} minutos menos por punto de aporte.`;case'form':return `${lead} llega con ${diff(a,b)} puntos más de forma reciente.`;case'community':return `${lead} tiene ${diff(a,b,1)} puntos porcentuales más de apoyo.`;default:return `${lead} sale por delante.`}}
function rCriteria(a,b){
  const ma=rMetric(a),mb=rMetric(b),ra=rRating(a),rb=rRating(b),pa=rPower(a),pb=rPower(b),fa=rRecent(a),fb=rRecent(b),community=rCommunityPair(a,b),an=displayName(a),bn=displayName(b);
  const rows=[
    {id:'rating',label:'Media actual',a:ra,b:rb,winner:cmpHigher(ra,rb),fmt:v=>v===null?'—':v.toFixed(2),note:'Media acumulada de las valoraciones oficiales del proyecto'},
    {id:'power',label:'Power RM',a:pa,b:pb,winner:cmpHigher(pa,pb),fmt:v=>v===null?'—':v.toFixed(2),note:'Rendimiento ajustado por tamaño de muestra'},
    {id:'minutes',label:'Minutos',a:ma?.minutes??null,b:mb?.minutes??null,winner:cmpHigher(ma?.minutes??null,mb?.minutes??null),fmt:v=>v===null?'—':`${v}'`,note:'Peso competitivo acumulado'},
    {id:'eff',label:'Eficiencia',a:ma?.minPerPoint??null,b:mb?.minPerPoint??null,winner:cmpLower(ma?.minPerPoint??null,mb?.minPerPoint??null),fmt:v=>v===null?'—':v.toFixed(2),note:'Menor min/punto = mejor eficiencia'},
    {id:'form',label:'Forma reciente',a:fa?.value??null,b:fb?.value??null,winner:cmpHigher(fa?.value??null,fb?.value??null),fmt:v=>v===null?'—':v.toFixed(2),note:`Últimas notas disponibles · muestra ${fa?.n||0}/${fb?.n||0}`},
    {id:'community',label:'Comunidad',a:community?.a??null,b:community?.b??null,winner:cmpHigher(community?.a??null,community?.b??null),fmt:v=>v===null?'—':`${v.toFixed(1)}%`,note:community?`${community.source} · ${community.total} voto${community.total===1?'':'s'}`:(backendAvailable()?'Sin votos comparables todavía':'Pendiente hasta volver a la versión conectada')}
  ];
  rows.forEach(c=>c.why=whyText(c.id,c.winner,c.a,c.b,an,bn));return rows;
}
function rScore(criteria){let a=0,b=0,ties=0,pending=0;criteria.forEach(c=>{if(c.winner===1)a++;else if(c.winner===-1)b++;else if(c.winner===0)ties++;else pending++});return {a,b,ties,pending,available:criteria.length-pending}}
function rConfidence(a,b,criteria){
  const ma=rMetric(a),mb=rMetric(b),fa=rRecent(a),fb=rRecent(b);const minMinutes=Math.min(ma?.minutes||0,mb?.minutes||0),formMin=Math.min(fa?.n||0,fb?.n||0),core=criteria.filter(c=>c.id!=='community'&&c.winner!==null).length;
  const pct=Math.round((Math.min(minMinutes,450)/450*.5+Math.min(formMin,3)/3*.25+core/5*.25)*100);
  const level=pct>=75?'Alta':pct>=45?'Media':'Baja';return {pct,level,minMinutes,formMin,core};
}
function rVerdict(a,b,criteria){
  const score=rScore(criteria),confidence=rConfidence(a,b,criteria),margin=Math.abs(score.a-score.b),winner=score.a>score.b?a:score.b>score.a?b:null;
  if(confidence.level==='Baja'||confidence.core<4)return {type:'insufficient',label:'MUESTRA INSUFICIENTE',title:'Todavía no cerraría el duelo',copy:`La confianza es ${confidence.pct}%. El jugador con menos minutos tiene ${confidence.minMinutes}.`,winner,score,confidence};
  if(winner&&margin>=2)return {type:'advantage',label:'VENTAJA REAL',title:`${displayName(winner)} parte por delante`,copy:`Ventaja de ${margin} criterio${margin===1?'':'s'} con confianza ${confidence.level.toLowerCase()} (${confidence.pct}%).`,winner,score,confidence};
  return {type:'open',label:'DUELO ABIERTO',title:'No hay suficiente distancia para cerrarlo',copy:`El margen es de ${margin} criterio${margin===1?'':'s'} con confianza ${confidence.level.toLowerCase()} (${confidence.pct}%).`,winner,score,confidence};
}
function playerOption(name){const p=rPlayer(name);return `<option value="${rEsc(name)}">${rEsc(p?.short||p?.name||name)} · ${p?.pos||''}</option>`}
function ensureRadar(){if(document.getElementById('radar'))return;const section=document.createElement('section');section.id='radar';section.className='section';const comparator=document.getElementById('comparador');if(comparator)comparator.insertAdjacentElement('beforebegin',section);else document.querySelector('main')?.appendChild(section);const active=document.querySelector('.section.active')?.id||'inicio';document.getElementById('navDesktop').innerHTML=navHtml(false);document.getElementById('navMobile').innerHTML=navHtml(true);document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===active))}
function presetForPair(a,b){return R_PRESETS.find(p=>(p.a===a&&p.b===b)||(p.a===b&&p.b===a))}
function metricRow(c,a,b){const state=c.winner===1?'a':c.winner===-1?'b':c.winner===0?'tie':'pending';return `<div class="radar-metric ${state}"><div class="radar-value left ${c.winner===1?'win':''}"><b>${c.fmt(c.a)}</b><small>${rEsc(displayName(a))}</small></div><div class="radar-metric-center"><strong>${rEsc(c.label)}</strong><span>${rEsc(c.note)}</span><small class="radar-why">${rEsc(c.why)}</small>${c.winner===null?'<em>PENDIENTE</em>':c.winner===0?'<em>EMPATE</em>':`<em>${c.winner===1?'←':'→'} PUNTO</em>`}</div><div class="radar-value right ${c.winner===-1?'win':''}"><b>${c.fmt(c.b)}</b><small>${rEsc(displayName(b))}</small></div></div>`}
function miniProfile(name){const p=rPlayer(name),m=rMetric(name),rating=rRating(name),power=rPower(name),form=rRecent(name),sample=Math.min(100,Math.round((m?.minutes||0)/450*100));return `<button class="radar-player-card" onclick="openPlayerHub('${name.replace(/'/g,"\\'")}')"><div class="avatar">${initials(p?.short||name)}</div><div><h3>${rEsc(p?.short||name)}</h3><p>${rEsc(p?.role||'')}</p></div><div class="radar-mini"><span><b>${rating===null?'—':rating.toFixed(2)}</b><small>Media</small></span><span><b>${power===null?'—':power.toFixed(2)}</b><small>Power</small></span><span><b>${m?.minutes??'—'}</b><small>Min</small></span><span><b>${form?form.value.toFixed(2):'—'}</b><small>Forma</small></span></div><div class="radar-sample"><div><i style="width:${sample}%"></i></div><small>Muestra Power ${sample}%</small></div></button>`}
function renderRadar(){
  const section=document.getElementById('radar');if(!section)return;const criteria=rCriteria(radarA,radarB),verdict=rVerdict(radarA,radarB,criteria),score=verdict.score,preset=presetForPair(radarA,radarB),audit=season()?.audit(),connected=backendAvailable();
  section.innerHTML=`<div class="section-head"><div><div class="eyebrow">RADAR PRO</div><h2>Radar de decisiones</h2><p>Compara datos, fiabilidad de la muestra y contexto antes de cerrar un debate.</p></div><button class="btn" onclick="refreshDecisionRadar()" ${connected?'':'disabled'}>${radarLoading?'Actualizando…':connected?'Actualizar comunidad':'Comunidad pendiente'}</button></div>
  <div class="radar-presets">${R_PRESETS.map(p=>`<button class="${preset?.id===p.id?'active':''}" onclick="selectRadarPreset('${p.id}')"><span>${rEsc(p.label)}</span><b>${rEsc(displayName(p.a))} vs ${rEsc(displayName(p.b))}</b></button>`).join('')}</div>
  <div class="card radar-custom"><div><div class="eyebrow">COMPARACIÓN LIBRE</div><h3>Elige cualquier pareja de la plantilla</h3></div><div class="radar-selects"><select class="select" id="radarSelectA" aria-label="Primer jugador del Radar" onchange="setRadarPlayers(this.value,null)">${players.map(p=>playerOption(p.name)).join('')}</select><span>VS</span><select class="select" id="radarSelectB" aria-label="Segundo jugador del Radar" onchange="setRadarPlayers(null,this.value)">${players.map(p=>playerOption(p.name)).join('')}</select></div></div>
  <div class="radar-decision ${verdict.type}"><div><span>${verdict.label}</span><h2>${rEsc(verdict.title)}</h2><p>${rEsc(verdict.copy)}</p></div><div class="radar-confidence"><strong>${verdict.confidence.pct}%</strong><span>confianza</span><div><i style="width:${verdict.confidence.pct}%"></i></div><small>${verdict.confidence.minMinutes} min mínimos · ${verdict.confidence.formMin}/3 forma</small></div></div>
  <div class="radar-scoreboard card"><div class="radar-score-name"><span>${rEsc(displayName(radarA))}</span><b>${score.a}</b></div><div class="radar-verdict"><div class="eyebrow">MARCADOR DEL RADAR</div><h2>${score.a===score.b?`Empate ${score.a}–${score.b}`:`${rEsc(displayName(score.a>score.b?radarA:radarB))} ${Math.max(score.a,score.b)}–${Math.min(score.a,score.b)}`}</h2><p>${preset?rEsc(preset.note):'Comparación libre de los seis indicadores.'}</p><div><span class="tag">${score.available}/6 disponibles</span>${score.ties?`<span class="tag">${score.ties} empate${score.ties===1?'':'s'}</span>`:''}${score.pending?`<span class="tag gold">${score.pending} pendiente${score.pending===1?'':'s'}</span>`:''}</div></div><div class="radar-score-name right"><span>${rEsc(displayName(radarB))}</span><b>${score.b}</b></div></div>
  <div class="radar-player-grid">${miniProfile(radarA)}${miniProfile(radarB)}</div>
  <div class="card radar-metrics"><div class="section-head" style="margin-top:0"><div><h2>Por qué gana cada criterio</h2><p>No solo mostramos el punto: explicamos la diferencia que lo provoca.</p></div></div>${criteria.map(c=>metricRow(c,radarA,radarB)).join('')}</div>
  <div class="radar-summary-grid"><div class="card"><div class="eyebrow">LECTURA DEL DUELO</div><h3>${rEsc(verdict.label)}</h3><p>${rEsc(verdict.copy)}</p></div><div class="card"><div class="eyebrow">FIABILIDAD</div><h3>${verdict.confidence.level} · ${verdict.confidence.pct}%</h3><p>50% depende de los minutos del jugador con menos muestra, 25% de forma reciente y 25% de cobertura de métricas base.</p></div><div class="card"><div class="eyebrow">TRAZABILIDAD</div><h3>${audit?.ratings?.confirmed||0} notas confirmadas</h3><p>SC nunca suma como cero. Comunidad solo entra cuando existen votos reales comparables.</p></div></div>
  <div class="radar-actions"><button class="btn primary" onclick="radarToComparator()">Abrir en Comparador PRO</button><button class="btn" onclick="radarToLineup()">Probar en Constructor</button><button class="btn" onclick="openPlayerHub('${radarA.replace(/'/g,"\\'")}')">Ficha ${rEsc(displayName(radarA))}</button><button class="btn" onclick="openPlayerHub('${radarB.replace(/'/g,"\\'")}')">Ficha ${rEsc(displayName(radarB))}</button></div>
  <div class="radar-integrity"><b>Cómo leer este Radar</b><span>El marcador sigue siendo transparente y sin pesos ocultos: cada criterio disponible vale un punto. La confianza no cambia el marcador; solo indica cuánto nos podemos fiar de la comparación. Rival, descanso y complementariedad táctica siguen quedando fuera del cálculo.</span>${!connected?'<small>GitHub Pages no consulta funciones de Netlify: la ronda Comunidad queda pendiente sin hacer peticiones inútiles.</small>':''}</div>`;
  const sa=document.getElementById('radarSelectA'),sb=document.getElementById('radarSelectB');if(sa)sa.value=radarA;if(sb)sb.value=radarB;window.RMAccessibility?.refresh?.();
}
window.selectRadarPreset=function(id){const p=R_PRESETS.find(x=>x.id===id);if(!p)return;radarA=p.a;radarB=p.b;renderRadar()};
window.setRadarPlayers=function(a,b){if(a)radarA=a;if(b)radarB=b;if(radarA===radarB){const alt=players.find(p=>p.name!==radarA);if(b)radarA=alt?.name||radarA;else radarB=alt?.name||radarB}renderRadar()};
window.radarToComparator=function(){showSection('comparador');const A=document.getElementById('compareA'),B=document.getElementById('compareB');if(A)A.value=radarA;if(B)B.value=radarB;if(typeof renderCompare==='function')renderCompare();setTimeout(()=>window.RMComparePro?.render?.(),0)};
window.radarToLineup=function(){const v=rVerdict(radarA,radarB,rCriteria(radarA,radarB));showSection('once');try{if(typeof toast==='function')toast(v.winner&&v.type==='advantage'?`Candidato del Radar: ${displayName(v.winner)}`:'Duelo abierto: prueba ambas variantes en el Constructor')}catch{};setTimeout(()=>window.RMLineupPro?.render?.(),0)};
window.refreshDecisionRadar=async function(){if(radarLoading)return;if(!backendAvailable()){radarCommunity=null;radarPolls=null;renderRadar();return}radarLoading=true;renderRadar();try{const pid=typeof getParticipantId==='function'?getParticipantId():'';const [c,p]=await Promise.all([fetch('/.netlify/functions/community-v2',{headers:{accept:'application/json'}}).then(r=>r.ok?r.json():null).catch(()=>null),fetch(`/.netlify/functions/matchday?participantId=${encodeURIComponent(pid)}`,{headers:{accept:'application/json'}}).then(r=>r.ok?r.json():null).catch(()=>null)]);radarCommunity=c;radarPolls=p}finally{radarLoading=false;renderRadar()}};
document.addEventListener('rm-community-updated',e=>{if(e.detail){radarCommunity=e.detail;renderRadar()}});
function install(){if(!season()||typeof sections==='undefined'||typeof players==='undefined'||typeof metricFor!=='function'){setTimeout(install,100);return}ensureRadar();renderRadar()}
window.RMDecisionRadar=Object.freeze({render:renderRadar,players:()=>[radarA,radarB],verdict:()=>rVerdict(radarA,radarB,rCriteria(radarA,radarB)),refresh:window.refreshDecisionRadar});
install();
})();