(()=>{
let intelCommunity=window.RMCommunityData||null,intelPolls=null,intelMvp=null,intelLoading=false;
function season(){return window.RMSeasonData}
function backendAvailable(){return typeof communityBackendAvailable==='function'?communityBackendAvailable():(/^https?:$/.test(location.protocol)&&!location.hostname.endsWith('github.io'))}
function iEsc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function iMetric(p){return metricFor(p)}
function iRating(p){const m=iMetric(p);return currentRating(m)}
function iPower(p){const m=iMetric(p),r=iRating(p);if(!m||r===null)return null;const sample=Math.min(m.minutes,450)/450;return r*(.75+.25*sample)}
function iPowerRows(){return players.map(p=>{const m=iMetric(p),rating=iRating(p),power=iPower(p);return m&&rating!==null?{p,m,rating,power,sample:Math.min(m.minutes,450)/450}:null}).filter(Boolean).sort((a,b)=>b.power-a.power||b.rating-a.rating)}
function iRecentAvg(name){return season()?.recentRating(name,3)||null}
function iSeries(name){return season()?.ratingSeries(name)||[]}
function iPlayerConfidence(p){const m=iMetric(p),matches=season()?.matches||[],rated=iSeries(p.name).length,sample=Math.min(m?.minutes||0,450)/450,coverage=matches.length?rated/matches.length:0;return Math.round(100*(.65*sample+.35*coverage))}
function iConfidenceLabel(value){return value>=80?'Alta':value>=60?'Media':value>=40?'Baja':'Muy baja'}
function iShortSample(){return iPowerRows().filter(x=>x.m.minutes<90).sort((a,b)=>b.rating-a.rating)[0]||null}
function iBestBench(){const base=new Set(Object.values(baseXI));return iPowerRows().find(x=>!base.has(x.p.name))||null}
function iNorm(v,min,max){if(!Number.isFinite(v))return 0;if(!Number.isFinite(min)||!Number.isFinite(max)||max===min)return 10;return Math.max(0,Math.min(10,10*(v-min)/(max-min)))}
function iBalanceParts(p){
  const rows=iPowerRows(),m=iMetric(p),r=iRating(p);if(!m||r===null)return null;
  const ratings=rows.map(x=>x.rating).filter(Number.isFinite),effs=rows.map(x=>x.m.minPerPoint).filter(Number.isFinite),rMin=Math.min(...ratings),rMax=Math.max(...ratings),eMin=Math.min(...effs),eMax=Math.max(...effs);
  const ratingScore=iNorm(r,rMin,rMax),sampleScore=Math.min(m.minutes,450)/45,effScore=Number.isFinite(m.minPerPoint)?iNorm(eMax-m.minPerPoint,0,eMax-eMin):0;
  return {ratingScore,sampleScore,effScore,score:.45*ratingScore+.30*sampleScore+.25*effScore};
}
function iBalanceScore(p){return iBalanceParts(p)?.score??null}
function iCandidates(slot){return players.filter(p=>p.eligible.includes(slot[4])&&iBalanceScore(p)!==null).map(p=>({p,score:iBalanceScore(p)})).sort((a,b)=>b.score-a.score)}
function iDataXI(){
  const ordered=slots.map(slot=>({slot,cands:iCandidates(slot)})).sort((a,b)=>a.cands.length-b.cands.length);let best=null,bestScore=-Infinity;const maxRemain=ordered.map((_,i)=>ordered.slice(i).reduce((s,x)=>s+(x.cands[0]?.score||0),0));
  function dfs(i,used,assign,total){if(i===ordered.length){if(total>bestScore){bestScore=total;best={...assign}}return}if(total+(maxRemain[i]||0)<=bestScore)return;const item=ordered[i];for(const c of item.cands){if(used.has(c.p.name))continue;used.add(c.p.name);assign[item.slot[0]]=c.p.name;dfs(i+1,used,assign,total+c.score);delete assign[item.slot[0]];used.delete(c.p.name)}}
  dfs(0,new Set(),{},0);return best||{};
}
function iOverlap(a,b){const A=new Set(Object.values(a||{}).filter(Boolean)),B=new Set(Object.values(b||{}).filter(Boolean));return [...A].filter(x=>B.has(x)).length}
function iDifferences(a,b){const A=new Set(Object.values(a||{}).filter(Boolean));return Object.values(b||{}).filter(Boolean).filter(x=>!A.has(x))}
function iXIConfidence(xi){const names=Object.values(xi||{}).filter(Boolean),vals=names.map(n=>players.find(p=>p.name===n)).filter(Boolean).map(iPlayerConfidence);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0}
function iReason(name){const p=players.find(x=>x.name===name),parts=p?iBalanceParts(p):null;if(!parts)return 'sin señal suficiente';const keys=[['ratingScore','rendimiento'],['sampleScore','muestra'],['effScore','eficiencia']].sort((a,b)=>parts[b[0]]-parts[a[0]]);return keys[0][1]}
function iLatestPair(){const ms=season()?.matches||[];return ms.length>=2?{previous:ms.at(-2),current:ms.at(-1)}:null}
function iAdjacentChanges(){const pair=iLatestPair();if(!pair)return [];return players.map(p=>{const a=season()?.officialRatingEntry(pair.previous.id,p.name),b=season()?.officialRatingEntry(pair.current.id,p.name);if(!Number.isFinite(a?.value)||!Number.isFinite(b?.value))return null;return {p,previous:a.value,current:b.value,delta:b.value-a.value,pair,confidence:iPlayerConfidence(p)}}).filter(Boolean).sort((a,b)=>b.delta-a.delta)}
function iBiggestRise(){return iAdjacentChanges().find(x=>x.delta>0)||null}
function iBiggestFall(){return [...iAdjacentChanges()].reverse().find(x=>x.delta<0)||null}
function iBiggestCommunityDebate(){let best=null;for(const [slot,rows] of Object.entries(intelCommunity?.slotShares||{})){if(!rows||rows.length<2)continue;const margin=Math.abs(rows[0].percentage-rows[1].percentage);if(!best||margin<best.margin)best={slot,margin,a:rows[0],b:rows[1]}}return best}
function iMostUnanimous(){let best=null;for(const rows of Object.values(intelCommunity?.slotShares||{})){if(!rows?.[0])continue;if(!best||rows[0].percentage>best.percentage)best=rows[0]}return best}
function iMvpLeader(){return intelMvp?.season?.[0]||null}
function iPoll(id){return (intelPolls?.polls||[]).find(p=>p.id===id)||null}
function iPollLead(id){const p=iPoll(id);if(!p||!p.total)return null;const rows=[...(p.options||[])].sort((a,b)=>b.percentage-a.percentage);return {poll:p,first:rows[0],second:rows[1]||null}}
function iDecisionCards(){const defs=[{id:'ld',title:'Lateral derecho',fallback:'Dumfries vs Trent'},{id:'central',title:'Jerarquía de centrales',fallback:'Rüdiger vs Konaté vs Huijsen'},{id:'banda',title:'Banda derecha',fallback:'Diomandé vs Brahim'}];return defs.map(d=>{const lead=iPollLead(d.id);if(!lead)return {...d,text:d.fallback,sub:backendAvailable()?'Pendiente de voto comunitario':'Resolver con Radar y datos'};const gap=lead.second?Math.abs(lead.first.percentage-lead.second.percentage):lead.first.percentage;return {...d,text:`${lead.first.label} · ${lead.first.percentage}%`,sub:lead.second?`${lead.second.label} ${lead.second.percentage}% · margen ${gap.toFixed(1)} pts`:`${lead.poll.total} votos`}})}
function ensureIntel(){if(document.getElementById('intelligenceHome'))return;const inicio=document.getElementById('inicio');if(!inicio)return;const block=document.createElement('div');block.id='intelligenceHome';block.className='intelligence-home';const hero=inicio.querySelector('.hero');if(hero)hero.insertAdjacentElement('afterend',block);else inicio.prepend(block)}
function changeCard(row,type){if(!row)return `<div class="intel-change-card empty"><span>${type==='up'?'SUBIDA':'CAÍDA'}</span><b>Sin comparación directa</b><small>Se necesitan notas en las dos últimas jornadas.</small></div>`;const sign=row.delta>=0?'+':'';return `<button class="intel-change-card ${type}" onclick="openPlayerHub('${row.p.name.replace(/'/g,"\\'")}')"><span>${type==='up'?'▲ MAYOR SUBIDA':'▼ MAYOR CAÍDA'}</span><b>${iEsc(row.p.short||row.p.name)}</b><strong>${sign}${row.delta.toFixed(2)}</strong><small>${row.previous.toFixed(2)} → ${row.current.toFixed(2)} · respaldo ${row.confidence}%</small></button>`}
function renderIntel(){
  const root=document.getElementById('intelligenceHome');if(!root||!season())return;
  const power=iPowerRows(),top=power[0]||null,rise=iBiggestRise(),fall=iBiggestFall(),short=iShortSample(),bench=iBestBench(),dataXI=iDataXI(),overlap=iOverlap(dataXI,rayoXI),changes=iDifferences(rayoXI,dataXI),xiConfidence=iXIConfidence(dataXI),debate=iBiggestCommunityDebate(),unanimous=iMostUnanimous(),mvp=iMvpLeader(),decisions=iDecisionCards(),audit=season()?.audit(),pair=iLatestPair(),online=backendAvailable();
  const communityReady=Boolean(intelCommunity?.totalPredictions),pollReady=Boolean((intelPolls?.polls||[]).some(p=>p.total)),mvpReady=Boolean(intelMvp?.totalVotes),leaderConfidence=top?iPlayerConfidence(top.p):0;
  root.innerHTML=`<div class="intel-head"><div><div class="eyebrow">🧠 CENTRO DE INTELIGENCIA PRO</div><h2>Qué está pasando ahora mismo</h2><p>Power, forma, muestra, cambios entre jornadas y decisiones tácticas en una sola lectura.</p></div><div class="intel-head-actions"><button class="btn" onclick="showSection('power')">Abrir Power</button><button class="btn" onclick="refreshIntelligence()">${intelLoading?'Actualizando…':online?'Actualizar señales':'Recalcular datos'}</button></div></div>
  <div class="intel-signal-grid"><button class="card intel-signal hero-signal" onclick="openPlayerHub('${top?.p.name?.replace(/'/g,"\\'")||''}')"><span>⚡ LÍDER POWER</span><b>${top?iEsc(top.p.short||top.p.name):'—'}</b><strong>${top?top.power.toFixed(2):'—'}</strong><small>${top?`Media ${top.rating.toFixed(2)} · ${top.m.minutes} min · respaldo ${leaderConfidence}%`:'Sin datos'}</small><i class="intel-confidence"><em style="width:${leaderConfidence}%"></em></i></button>
  <button class="card intel-signal" onclick="${rise?`openPlayerHub('${rise.p.name.replace(/'/g,"\\'")}')`:`showSection('evolucion')`}"><span>↗ SUBE ENTRE JORNADAS</span><b>${rise?iEsc(rise.p.short||rise.p.name):'—'}</b><strong>${rise?`+${rise.delta.toFixed(2)}`:'—'}</strong><small>${rise?`${rise.previous.toFixed(2)} → ${rise.current.toFixed(2)} · ${iEsc(rise.pair.current.short)}`:'Sin dos notas consecutivas'}</small></button>
  <button class="card intel-signal danger" onclick="${fall?`openPlayerHub('${fall.p.name.replace(/'/g,"\\'")}')`:`showSection('evolucion')`}"><span>↘ CAE ENTRE JORNADAS</span><b>${fall?iEsc(fall.p.short||fall.p.name):'—'}</b><strong>${fall?fall.delta.toFixed(2):'—'}</strong><small>${fall?`${fall.previous.toFixed(2)} → ${fall.current.toFixed(2)} · ${iEsc(fall.pair.current.short)}`:'Sin dos notas consecutivas'}</small></button>
  <button class="card intel-signal warning" onclick="${short?`openPlayerHub('${short.p.name.replace(/'/g,"\\'")}')`:`showSection('power')`}"><span>🔬 MUESTRA A VIGILAR</span><b>${short?iEsc(short.p.short||short.p.name):'—'}</b><strong>${short?short.m.minutes:'—'}<em> min</em></strong><small>${short?`Media ${short.rating.toFixed(2)} · Power ${short.power.toFixed(2)} · respaldo ${iPlayerConfidence(short.p)}%`:'Sin muestras cortas'}</small></button></div>
  <div class="card intel-changes"><div class="intel-card-head"><div><div class="eyebrow">QUÉ CAMBIÓ</div><h3>${pair?`${iEsc(pair.previous.short)} → ${iEsc(pair.current.short)}`:'Últimas jornadas'}</h3></div><button class="btn" onclick="showSection('evolucion')">Ver Evolución</button></div><div class="intel-change-grid">${changeCard(rise,'up')}${changeCard(fall,'down')}<div class="intel-change-card context"><span>LECTURA</span><b>${iAdjacentChanges().length} comparables directos</b><small>Solo jugadores con nota oficial en ambas jornadas. SC o ausencia no cuentan como 0.</small></div></div></div>
  <div class="intel-main-grid"><div class="card intel-xi-card"><div class="intel-card-head"><div><div class="eyebrow">⚗ XI POR DATOS</div><h3>Equilibrio del Laboratorio</h3></div><div class="intel-xi-actions"><button class="btn" onclick="showSection('laboratorio')">Laboratorio</button><button class="btn" onclick="showSection('jerarquias')">Jerarquías</button></div></div><div class="intel-xi-pitch">${slots.map(s=>`<div style="left:${s[2]}%;top:${s[3]}%"><small>${s[1]}</small><b>${iEsc(displayName(dataXI[s[0]]||'—'))}</b></div>`).join('')}</div><div class="intel-xi-summary"><div><span>Coincide con nuestra idea</span><b>${overlap}<small>/11</small></b></div><div><span>Cambios que propone</span><b>${11-overlap}</b></div><div><span>Respaldo de datos</span><b>${xiConfidence}%</b><small>${iConfidenceLabel(xiConfidence)}</small></div></div>${changes.length?`<div class="intel-change-line"><span>Entrarían por datos:</span>${changes.map(n=>`<button onclick="openPlayerHub('${n.replace(/'/g,"\\'")}')">${iEsc(displayName(n))}<small>${iEsc(iReason(n))}</small></button>`).join('')}</div>`:''}<div class="intel-xi-note">El XI por datos pondera <b>45% rendimiento · 30% muestra · 25% eficiencia</b>. El respaldo indica calidad de muestra, no probabilidad de ser titular.</div></div>
  <div class="card intel-community-card"><div class="intel-card-head"><div><div class="eyebrow">👥 COMUNIDAD</div><h3>${online?'Pulso compartido':'Backend en pausa aquí'}</h3></div><button class="btn" onclick="showSection('comunidad')">Ver comunidad</button></div>${online?`<div class="intel-community-signals"><div><span>Mayor debate</span><b>${debate?`${iEsc(displayName(debate.a.name))} ${debate.a.percentage}% · ${iEsc(displayName(debate.b.name))} ${debate.b.percentage}%`:'—'}</b><small>${debate?`Solo ${debate.margin.toFixed(1)} pts de margen`:(communityReady?'Sin duelo con dos opciones':'Esperando pronósticos')}</small></div><div><span>Más unánime</span><b>${unanimous?`${iEsc(displayName(unanimous.name))} · ${unanimous.percentage}%`:'—'}</b><small>${communityReady?`${intelCommunity.totalPredictions} pronóstico${intelCommunity.totalPredictions===1?'':'s'}`:'Comunidad pendiente'}</small></div><div><span>MVP comunidad</span><b>${mvp?iEsc(displayName(mvp.player)):'—'}</b><small>${mvpReady?`${mvp.wins||0} victorias · ${mvp.votes||0} votos`:'Esperando votos MVP'}</small></div></div>`:`<div class="intel-offline"><b>GitHub Pages usa solo señales locales y oficiales.</b><span>No se realizan llamadas a Netlify desde esta versión. Power, Evolución, Jerarquías, Radar y el XI por datos siguen funcionando completos.</span></div>`}<div class="intel-community-signals"><div><span>Histórico verificado</span><b>${audit?`${audit.ratings.confirmed} notas`:'—'}</b><small>${audit?`${audit.ratings.reconstructed} reconstruidas fuera de tendencias`:'Fuente pendiente'}</small></div><div><span>Mejor fuera del XI base</span><b>${bench?iEsc(bench.p.short||bench.p.name):'—'}</b><small>${bench?`Power ${bench.power.toFixed(2)} · ${bench.m.minutes} min`:'Sin candidato'}</small></div></div></div></div>
  <div class="intel-decisions-head"><div><div class="eyebrow">🎯 DECISIONES ABIERTAS</div><h2>3 dudas que pueden cambiar el XI</h2></div><button class="btn" onclick="showSection('radar')">Abrir Radar PRO</button></div><div class="intel-decisions">${decisions.map((d,i)=>`<button class="card" onclick="showSection('radar')"><span>0${i+1}</span><div><small>${iEsc(d.title)}</small><b>${iEsc(d.text)}</b><p>${iEsc(d.sub)}</p></div><strong>→</strong></button>`).join('')}</div>
  <div class="intel-status"><div><span>Power</span><b class="on">PRO</b></div><div><span>Evolución</span><b class="on">PRO</b></div><div><span>Jerarquías</span><b class="on">PRO</b></div><div><span>Radar</span><b class="on">PRO</b></div><div><span>Comunidad</span><b class="${online&&communityReady?'on':'wait'}">${online?(communityReady?'Conectada':'Sin datos'):'No consultada'}</b></div><div><span>MVP</span><b class="${online&&mvpReady?'on':'wait'}">${online?(mvpReady?'Conectado':'Sin datos'):'No consultado'}</b></div></div>`;
  document.dispatchEvent(new CustomEvent('rm-intelligence-rendered'));
}
async function iFetchJson(url){if(!backendAvailable())return null;try{const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)return null;return await r.json()}catch{return null}}
window.refreshIntelligence=async function(){
  if(intelLoading)return;
  if(!backendAvailable()){renderIntel();if(typeof toast==='function')toast('Señales locales recalculadas');return}
  intelLoading=true;renderIntel();const pid=typeof getParticipantId==='function'?getParticipantId():'';
  const [c,p,m]=await Promise.all([iFetchJson('/.netlify/functions/community-v2'),iFetchJson(`/.netlify/functions/matchday?participantId=${encodeURIComponent(pid)}`),iFetchJson(`/.netlify/functions/mvp?participantId=${encodeURIComponent(pid)}`)]);if(c)intelCommunity=c;if(p)intelPolls=p;if(m)intelMvp=m;intelLoading=false;renderIntel();
};
function hookCommunity(){if(typeof renderCommunity!=='function'||window.__rmIntelCommunityHook)return;window.__rmIntelCommunityHook=true;const base=renderCommunity;renderCommunity=function(data){base(data);intelCommunity=data;renderIntel()}}
function install(){if(!season()||typeof players==='undefined'||typeof slots==='undefined'||typeof metricFor!=='function'){setTimeout(install,120);return}ensureIntel();hookCommunity();renderIntel();if(backendAvailable())setTimeout(()=>refreshIntelligence(),350)}
window.RMIntelligencePro=Object.freeze({render:renderIntel,refresh:()=>refreshIntelligence(),backendAvailable,dataXI:iDataXI,changes:iAdjacentChanges});
['rm-ranking-official-ready','rm-power-official-ready','rm-season-data-ready'].forEach(name=>document.addEventListener(name,()=>setTimeout(renderIntel,0)));
install();
})();