(()=>{
const css=document.createElement('link');css.rel='stylesheet';css.href='matchday.css?v=6';css.dataset.matchdayCss='6';document.head.appendChild(css);
const performanceCss=document.createElement('link');performanceCss.rel='stylesheet';performanceCss.href='matchday-performance.css?v=2';performanceCss.dataset.matchdayPerformanceCss='2';document.head.appendChild(performanceCss);
const entry=['partido','⚽','Partido','Centro del partido','Tu XI, la comunidad y el once oficial con sus notas en una sola pantalla.'];
if(!sections.some(s=>s[0]==='partido'))sections.splice(1,0,entry);
document.getElementById('navDesktop').innerHTML=navHtml(false);document.getElementById('navMobile').innerHTML=navHtml(true);
let communityData=window.RMCommunityData||null,installed=false;
function safe(fn,fallback=null){try{return fn()}catch{return fallback}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function xmlEsc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&apos;','"':'&quot;'}[c]))}
function canonical(name){return safe(()=>window.RMSeasonData?.canonical?.(name),name)||name}
function display(name){return safe(()=>displayName(name),name)||name}
function official(){return safe(()=>Array.isArray(officialXI)?officialXI:null,null)}
function officialSlots(){return safe(()=>window.RMOfficialXIBySlot,null)||safe(()=>typeof officialXIBySlot!=='undefined'?officialXIBySlot:null,null)}
function mine(){return safe(()=>getSavedPrediction()?.xi,null)}
function values(xi){return Object.values(xi||{}).filter(Boolean)}
function valid(xi){const v=values(xi);return v.length===11&&new Set(v.map(canonical)).size===11}
function communityXi(){const out={};for(const s of safe(()=>slots,[])||[]){const row=communityData?.popularXI?.[s[0]];out[s[0]]=typeof row==='string'?row:row?.name||''}return valid(out)?out:null}
function score(xi){const real=official();if(!real||!valid(xi))return null;const set=new Set(real.map(canonical));return values(xi).filter(n=>set.has(canonical(n))).length}
function chips(xi,kind=''){const list=values(xi);return list.length?`<div class="md-lineup-chips ${kind}">${list.map(n=>`<span>${esc(display(n))}</span>`).join('')}</div>`:'<div class="md-empty">Todavía no disponible.</div>'}
function ensure(){if(document.getElementById('partido'))return document.getElementById('partido');const pred=document.getElementById('prediccion');if(!pred)return null;pred.insertAdjacentHTML('beforebegin','<section class="section" id="partido"><div id="matchdayDynamic"></div></section>');return document.getElementById('partido')}
function card(label,title,xi,action,section){const n=score(xi),ready=valid(xi);return `<article class="card md-xi-card"><div class="md-card-head"><span class="md-label">${esc(label)}</span><b>${n===null?(ready?'11 jugadores':'Pendiente'):`${n}/11`}</b></div><h3>${esc(title)}</h3>${chips(xi)}${action?`<button class="btn" data-md-go="${section}">${esc(action)}</button>`:''}</article>`}
function hero(){const rival=safe(()=>predictionMatch?.rival,'próximo rival'),real=official();return `<div class="section-head md-section-head"><div><h2>Centro del partido</h2><p>${real?'El XI oficial y su análisis quedan arriba; debajo puedes comparar tu pronóstico con el consenso.':'Tu XI y la comunidad frente al oficial, sin capas intermedias.'}</p></div><span class="pill ${real?'closed':'open'}">${real?'XI oficial publicado':'Previa'}</span></div><div class="matchday-hero"><div class="matchday-scoreboard"><div class="eyebrow">${real?'PARTIDO':'PRÓXIMO PARTIDO'}</div><h2>REAL MADRID <span>vs</span> ${esc(String(rival).toUpperCase())}</h2><h3 class="md-stage-title">${real?'El partido, de un vistazo':'Compara tu elección con el consenso'}</h3><p class="md-stage-copy">${real?'El once oficial y la lectura de sus notas aparecen primero; después quedan tu XI y el de la comunidad para la comparación.':'Antes del partido basta con ver en qué coincidís y en qué os diferenciáis.'}</p></div></div>`}
function currentSeasonMatch(){
  const data=window.RMSeasonData,rival=String(safe(()=>predictionMatch?.rival,'')||'').trim().toLocaleLowerCase('es-ES');if(!data||!rival)return null;
  return (data.matches||[]).find(m=>String(m.label||'').trim().toLocaleLowerCase('es-ES')===rival)||null;
}
function fmtRating(v){return Number.isFinite(v)?Number(v).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}
function ratingTone(v){if(!Number.isFinite(v))return 'pending';if(v>=8)return 'elite';if(v>=7)return 'good';if(v<6.5)return 'low';return 'normal'}
function ratingColor(v){if(!Number.isFinite(v))return '#8ea2b5';if(v>=8)return '#d8b44a';if(v>=7)return '#47d18c';if(v<6.5)return '#eb6969';return '#72a8d9'}
function playerInitials(name){return String(name||'').split(/[ .-]/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'RM'}
function performanceData(){
  const data=window.RMSeasonData,match=currentSeasonMatch(),slotMap=officialSlots(),real=official(),slotDefs=safe(()=>slots,[])||[];if(!data||!match||!slotMap||!real||slotDefs.length!==11)return null;
  const starters=slotDefs.map(s=>{const name=slotMap[s[0]]||'';if(!name)return null;const entry=safe(()=>data.officialRatingEntry?.(match.id,name),null),minutes=safe(()=>data.minutes?.(match.id,name),null);return {key:s[0],label:s[1],x:s[2],y:s[3],name,display:display(name),rating:entry?.value??null,entry,minutes:Number.isFinite(minutes)?minutes:null}}).filter(Boolean);
  if(starters.length!==11)return null;
  const rated=starters.filter(x=>Number.isFinite(x.rating)),avg=rated.length?rated.reduce((sum,x)=>sum+x.rating,0)/rated.length:null,starterSet=new Set(starters.map(x=>canonical(x.name)));
  const bench=(safe(()=>players,[])||[]).map(p=>{if(starterSet.has(canonical(p.name)))return null;const minutes=safe(()=>data.minutes?.(match.id,p.name),null);if(!Number.isFinite(minutes)||minutes<=0)return null;const entry=safe(()=>data.officialRatingEntry?.(match.id,p.name),null);return {name:p.name,display:display(p.name),minutes,rating:entry?.value??null,entry}}).filter(Boolean).sort((a,b)=>b.minutes-a.minutes);
  return {data,match,starters,rated,avg,bench};
}
function lineupSvg(p){
  const playersSvg=p.starters.map(row=>{
    const cx=80+(Number(row.x)||50)*8.4,cy=105+(Number(row.y)||50)*10.15,tone=ratingColor(row.rating),name=xmlEsc(row.display),rating=xmlEsc(fmtRating(row.rating)),mins=row.minutes!==null?`${row.minutes}'`:'';
    return `<g transform="translate(${cx.toFixed(1)} ${cy.toFixed(1)})"><circle r="48" fill="#102438" stroke="${tone}" stroke-width="4"/><text x="0" y="8" text-anchor="middle" fill="#f6f8fb" font-size="25" font-weight="800" font-family="Arial, sans-serif">${xmlEsc(playerInitials(row.display))}</text><rect x="23" y="-64" width="70" height="38" rx="19" fill="${tone}"/><text x="58" y="-38" text-anchor="middle" fill="#071421" font-size="21" font-weight="900" font-family="Arial, sans-serif">${rating}</text><text x="0" y="79" text-anchor="middle" fill="#ffffff" font-size="24" font-weight="800" font-family="Arial, sans-serif">${name}</text><text x="0" y="105" text-anchor="middle" fill="#9fb0c1" font-size="17" font-family="Arial, sans-serif">${xmlEsc(mins)}</text></g>`
  }).join('');
  const rival=xmlEsc(p.match?.label||safe(()=>predictionMatch?.rival,'Rival')),avg=xmlEsc(fmtRating(p.avg));
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1250" viewBox="0 0 1000 1250"><defs><linearGradient id="bg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#153f35"/><stop offset="1" stop-color="#09251f"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="10" stdDeviation="12" flood-color="#000" flood-opacity=".35"/></filter></defs><rect width="1000" height="1250" rx="34" fill="#071421"/><text x="60" y="62" fill="#d8b44a" font-size="24" font-weight="900" font-family="Arial, sans-serif" letter-spacing="2">XI OFICIAL · NOTA COMBINADA</text><text x="60" y="100" fill="#ffffff" font-size="34" font-weight="900" font-family="Arial, sans-serif">Real Madrid vs ${rival}</text><text x="940" y="78" text-anchor="end" fill="#ffffff" font-size="20" font-weight="700" font-family="Arial, sans-serif">Media XI</text><text x="940" y="108" text-anchor="end" fill="#d8b44a" font-size="34" font-weight="900" font-family="Arial, sans-serif">${avg}</text><rect x="54" y="138" width="892" height="1058" rx="28" fill="url(#bg)" stroke="#547a70" stroke-width="3"/><rect x="78" y="162" width="844" height="1010" fill="none" stroke="#d8e9e3" stroke-opacity=".32" stroke-width="3"/><line x1="78" y1="667" x2="922" y2="667" stroke="#d8e9e3" stroke-opacity=".32" stroke-width="3"/><circle cx="500" cy="667" r="92" fill="none" stroke="#d8e9e3" stroke-opacity=".32" stroke-width="3"/><circle cx="500" cy="667" r="5" fill="#d8e9e3" fill-opacity=".45"/><rect x="333" y="162" width="334" height="130" fill="none" stroke="#d8e9e3" stroke-opacity=".32" stroke-width="3"/><rect x="408" y="162" width="184" height="55" fill="none" stroke="#d8e9e3" stroke-opacity=".32" stroke-width="3"/><rect x="333" y="1042" width="334" height="130" fill="none" stroke="#d8e9e3" stroke-opacity=".32" stroke-width="3"/><rect x="408" y="1117" width="184" height="55" fill="none" stroke="#d8e9e3" stroke-opacity=".32" stroke-width="3"/><g filter="url(#shadow)">${playersSvg}</g></svg>`
}
function lineupImageHtml(p){const svg=lineupSvg(p),src=`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;return `<figure class="md-official-lineup-image"><img src="${src}" alt="XI oficial del Real Madrid contra ${esc(p.match?.label||'el rival')} con la nota combinada de cada titular"><figcaption>Nota combinada de SofaScore + FotMob + StatMuse. La imagen se genera automáticamente con el XI y las notas de la jornada.</figcaption></figure>`}
function analysisHtml(p){
  const ordered=[...p.rated].sort((a,b)=>b.rating-a.rating||b.minutes-a.minutes),top=ordered.slice(0,3),low=[...ordered].sort((a,b)=>a.rating-b.rating||b.minutes-a.minutes).slice(0,3),complete=p.starters.filter(x=>x.entry?.complete).length;
  const topText=top.length?top.map((x,i)=>`${i?i===top.length-1?' y ':', ':''}${display(x.name)} (${fmtRating(x.rating)})`).join(''): 'Sin notas cerradas';
  const lowText=low.length?low.map((x,i)=>`${i?i===low.length-1?' y ':', ':''}${display(x.name)} (${fmtRating(x.rating)})`).join(''): 'Sin notas cerradas';
  return `<article class="md-match-analysis"><div class="md-analysis-head"><div><span class="md-label">ANÁLISIS DEL PARTIDO</span><h3>Lectura de las notas</h3></div><div class="md-analysis-average"><small>Media XI</small><b>${fmtRating(p.avg)}</b></div></div><p class="md-analysis-intro">Análisis objetivo a partir de las valoraciones combinadas de SofaScore, FotMob y StatMuse.</p><div class="md-analysis-points"><div><span>★</span><p><b>Mejores medias.</b> ${esc(topText)}.</p></div><div><span>↘</span><p><b>Zona más baja.</b> ${esc(lowText)}.</p></div><div><span>✓</span><p><b>Cobertura.</b> ${complete}/11 titulares tienen las tres fuentes cerradas${complete===11?' y la comparación del XI es completa.':'.'}</p></div></div></article>`
}
function subsHtml(p){if(!p.bench.length)return '';return `<details class="md-used-subs"><summary><span>SUPLENTES UTILIZADOS</span><b>${p.bench.length}</b><strong>+</strong></summary><div class="md-sub-list">${p.bench.map(x=>`<div><span><b>${esc(x.display)}</b><small>${x.minutes}'${x.entry?.complete?' · 3/3':x.entry?.status==='closed-partial'?` · ${x.entry.sourceCount}+SC`:''}</small></span><strong class="${ratingTone(x.rating)}">${fmtRating(x.rating)}</strong></div>`).join('')}</div></details>`}
function performanceHtml(){
  const p=performanceData();if(!official())return '';
  if(!p)return `<section class="card md-performance md-performance-wait"><div><span class="md-label">XI OFICIAL · NOTAS MEDIAS</span><h2>Notas en revisión</h2><p>El XI oficial ya está publicado. La imagen aparecerá automáticamente cuando las valoraciones del partido estén cerradas en la base de temporada.</p></div></section>`;
  return `<section class="card md-performance"><div class="section-head md-performance-title" style="margin-top:0"><div><span class="md-label">XI OFICIAL · NOTAS MEDIAS</span><h2>Once confirmado</h2><p>Representación visual del XI oficial con la media combinada de cada titular.</p></div><div class="md-team-rating"><span>MEDIA DEL XI</span><b>${fmtRating(p.avg)}</b><small>${p.starters.filter(x=>x.entry?.complete).length}/11 con 3/3</small></div></div><div class="md-performance-grid md-performance-image-grid">${lineupImageHtml(p)}${analysisHtml(p)}</div>${subsHtml(p)}</section>`
}
function render(){const section=ensure();if(!section)return;let root=document.getElementById('matchdayDynamic');if(!root){root=document.createElement('div');root.id='matchdayDynamic';section.appendChild(root)}const user=mine(),community=communityXi();root.innerHTML=`${performanceHtml()}${hero()}<div class="md-xi-grid md-xi-grid-two">${card('TU PREDICCIÓN','Tu XI',user,'Ver mi predicción','prediccion')}${card('COMUNIDAD','XI más votado',community,'Ver comunidad','comunidad')}</div>`;root.querySelectorAll('[data-md-go]').forEach(b=>b.addEventListener('click',()=>safe(()=>showSection(b.dataset.mdGo))));}
function loadCommunity(){if(window.RMCommunityData){communityData=window.RMCommunityData;render();return}safe(()=>window.RMCommunityApi?.refresh?.())}
function install(){if(installed)return;const section=ensure();if(!section){setTimeout(install,100);return}installed=true;render();const base=showSection;showSection=function(id){base(id);if(id==='partido'){loadCommunity();setTimeout(render,0)}};document.addEventListener('rm-community-updated',e=>{communityData=e.detail||window.RMCommunityData||communityData;render()});document.addEventListener('rm-local-prediction-updated',render);document.addEventListener('rm-ranking-official-ready',render);document.addEventListener('rm-season-data-ready',()=>setTimeout(render,20));document.addEventListener('rm-season-extension-ready',()=>setTimeout(render,20));window.RMMatchdayCenter=Object.freeze({render,refresh:loadCommunity,performance:performanceData})}
install();
})();