(()=>{
const css=document.createElement('link');css.rel='stylesheet';css.href='matchday.css?v=4';css.dataset.matchdayCss='4';document.head.appendChild(css);
const entry=['partido','⚽','Partido','Centro del partido','Tu XI, la comunidad y el XI oficial en una sola pantalla.'];
if(!sections.some(s=>s[0]==='partido'))sections.splice(1,0,entry);
document.getElementById('navDesktop').innerHTML=navHtml(false);document.getElementById('navMobile').innerHTML=navHtml(true);
let communityData=window.RMCommunityData||null,installed=false;
function safe(fn,fallback=null){try{return fn()}catch{return fallback}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function canonical(name){return safe(()=>window.RMSeasonData?.canonical?.(name),name)||name}
function display(name){return safe(()=>displayName(name),name)||name}
function official(){return safe(()=>Array.isArray(officialXI)?officialXI:null,null)}
function mine(){return safe(()=>getSavedPrediction()?.xi,null)}
function values(xi){return Object.values(xi||{}).filter(Boolean)}
function valid(xi){const v=values(xi);return v.length===11&&new Set(v.map(canonical)).size===11}
function communityXi(){const out={};for(const s of safe(()=>slots,[])||[]){const row=communityData?.popularXI?.[s[0]];out[s[0]]=typeof row==='string'?row:row?.name||''}return valid(out)?out:null}
function score(xi){const real=official();if(!real||!valid(xi))return null;const set=new Set(real.map(canonical));return values(xi).filter(n=>set.has(canonical(n))).length}
function chips(xi,kind=''){const list=values(xi);return list.length?`<div class="md-lineup-chips ${kind}">${list.map(n=>`<span>${esc(display(n))}</span>`).join('')}</div>`:'<div class="md-empty">Todavía no disponible.</div>'}
function ensure(){if(document.getElementById('partido'))return document.getElementById('partido');const pred=document.getElementById('prediccion');if(!pred)return null;pred.insertAdjacentHTML('beforebegin','<section class="section" id="partido"><div id="matchdayDynamic"></div></section>');return document.getElementById('partido')}
function card(label,title,xi,action,section){const n=score(xi),ready=valid(xi);return `<article class="card md-xi-card ${label==='XI OFICIAL'&&ready?'official':''}"><div class="md-card-head"><span class="md-label">${esc(label)}</span><b>${n===null?(ready?'11 jugadores':'Pendiente'):`${n}/11`}</b></div><h3>${esc(title)}</h3>${chips(xi,label==='XI OFICIAL'?'official':'')}${action?`<button class="btn" data-md-go="${section}">${esc(action)}</button>`:''}</article>`}
function hero(){const rival=safe(()=>predictionMatch?.rival,'próximo rival'),real=official();return `<div class="section-head md-section-head"><div><h2>Centro del partido</h2><p>Tu XI y la comunidad frente al oficial, sin capas intermedias.</p></div><span class="pill ${real?'closed':'open'}">${real?'XI oficial publicado':'Previa'}</span></div><div class="matchday-hero"><div class="matchday-scoreboard"><div class="eyebrow">${real?'XI OFICIAL':'PRÓXIMO PARTIDO'}</div><h2>REAL MADRID <span>vs</span> ${esc(String(rival).toUpperCase())}</h2><h3 class="md-stage-title">${real?'Compara quién acertó más':'Compara tu elección con el consenso'}</h3><p class="md-stage-copy">${real?'La misma regla para ambos: un punto por cada titular presente en el once oficial.':'Antes del partido basta con ver en qué coincidís y en qué os diferenciáis.'}</p></div></div>`}
function diffBlock(user,community){if(!valid(user)||!valid(community))return '';const A=new Set(values(user).map(canonical)),B=new Set(values(community).map(canonical)),same=values(user).filter(n=>B.has(canonical(n))),onlyMine=values(user).filter(n=>!B.has(canonical(n))),onlyCommunity=values(community).filter(n=>!A.has(canonical(n)));return `<section class="card md-differences"><div class="section-head" style="margin-top:0"><div><span class="md-label">TU XI VS COMUNIDAD</span><h2>${same.length}/11 coincidencias</h2><p>Las diferencias se leen por jugador, no por posición exacta.</p></div></div><div class="md-diff-grid"><div><span>Solo en tu XI</span>${chips(Object.fromEntries(onlyMine.map((n,i)=>[i,n])),'miss')}</div><div><span>Solo comunidad</span>${chips(Object.fromEntries(onlyCommunity.map((n,i)=>[i,n])),'surprise')}</div></div></section>`}
function render(){const section=ensure();if(!section)return;let root=document.getElementById('matchdayDynamic');if(!root){root=document.createElement('div');root.id='matchdayDynamic';section.appendChild(root)}const user=mine(),community=communityXi(),real=official();root.innerHTML=`${hero()}<div class="md-xi-grid">${card('TU PREDICCIÓN','Tu XI',user,'Ver mi predicción','prediccion')}${card('COMUNIDAD','XI más votado',community,'Ver comunidad','comunidad')}${card('XI OFICIAL','Once confirmado',real,null,null)}</div>${diffBlock(user,community)}${real?`<section class="card md-community"><div class="section-head" style="margin-top:0"><div><span class="md-label">RESULTADO</span><h2>Tu XI y la comunidad frente al oficial</h2><p>Tú: <b>${score(user)??'—'}/11</b> · Comunidad: <b>${score(community)??'—'}/11</b>.</p></div></div></section>`:''}`;root.querySelectorAll('[data-md-go]').forEach(b=>b.addEventListener('click',()=>safe(()=>showSection(b.dataset.mdGo))));}
function loadCommunity(){if(window.RMCommunityData){communityData=window.RMCommunityData;render();return}safe(()=>window.RMCommunityApi?.refresh?.())}
function install(){if(installed)return;const section=ensure();if(!section){setTimeout(install,100);return}installed=true;render();const base=showSection;showSection=function(id){base(id);if(id==='partido'){loadCommunity();setTimeout(render,0)}};document.addEventListener('rm-community-updated',e=>{communityData=e.detail||window.RMCommunityData||communityData;render()});document.addEventListener('rm-local-prediction-updated',render);document.addEventListener('rm-ranking-official-ready',render);window.RMMatchdayCenter=Object.freeze({render,refresh:loadCommunity})}
install();
})();