(()=>{
const css=document.createElement('link');css.rel='stylesheet';css.href='matchday.css?v=5';css.dataset.matchdayCss='5';document.head.appendChild(css);
const performanceCss=document.createElement('link');performanceCss.rel='stylesheet';performanceCss.href='matchday-performance.css?v=1';performanceCss.dataset.matchdayPerformanceCss='1';document.head.appendChild(performanceCss);
const entry=['partido','⚽','Partido','Centro del partido','Tu XI, la comunidad, la alineación oficial y el análisis del partido en una sola pantalla.'];
if(!sections.some(s=>s[0]==='partido'))sections.splice(1,0,entry);
document.getElementById('navDesktop').innerHTML=navHtml(false);document.getElementById('navMobile').innerHTML=navHtml(true);
let communityData=window.RMCommunityData||null,installed=false;
function safe(fn,fallback=null){try{return fn()}catch{return fallback}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function canonical(name){return safe(()=>window.RMSeasonData?.canonical?.(name),name)||name}
function display(name){return safe(()=>displayName(name),name)||name}
function official(){return safe(()=>Array.isArray(officialXI)?officialXI:null,null)}
function officialSlots(){return safe(()=>window.RMOfficialXIBySlot,null)||safe(()=>typeof officialXIBySlot!=='undefined'?officialXIBySlot:null,null)}
function mine(){return safe(()=>getSavedPrediction()?.xi,null)}
function values(xi){return Object.values(xi||{}).filter(Boolean)}
function valid(xi){const v=values(xi);return v.length===11&&new Set(v.map(canonical)).size===11}
function communityXi(){const out={};for(const s of safe(()=>slots,[])||[]){const row=communityData?.popularXI?.[s[0]];out[s[0]]=typeof row==='string'?row:row?.name||''}return valid(out)?out:null}
function score(xi){const real=official();if(!real||!valid(xi))return null;const set=new Set(real.map(canonical));return values(xi).filter(n=>set.has(canonical(n))).length}
function chips(xi,kind=''){const list=values(xi);return list.length?`<div class="md-lineup-chips ${kind}">${list.map(n=>`<span>${esc(display(n))}</span>`).join('')}</div>`:'<div class="md-empty">Todavía no disponible.</div>'}
function ensure(){if(document.getElementById('partido'))return document.getElementById('partido');const pred=document.getElementById('prediccion');if(!pred)return null;pred.insertAdjacentHTML('beforebegin','<section class="section" id="partido"><div id="matchdayDynamic"></div></section>');return document.getElementById('partido')}
function card(label,title,xi,action,section){const n=score(xi),ready=valid(xi);return `<article class="card md-xi-card ${label==='XI OFICIAL'&&ready?'official':''}"><div class="md-card-head"><span class="md-label">${esc(label)}</span><b>${n===null?(ready?'11 jugadores':'Pendiente'):`${n}/11`}</b></div><h3>${esc(title)}</h3>${chips(xi,label==='XI OFICIAL'?'official':'')}${action?`<button class="btn" data-md-go="${section}">${esc(action)}</button>`:''}</article>`}
function hero(){const rival=safe(()=>predictionMatch?.rival,'próximo rival'),real=official();return `<div class="section-head md-section-head"><div><h2>Centro del partido</h2><p>${real?'Alineación, notas medias, análisis y resultado de las predicciones.':'Tu XI y la comunidad frente al oficial, sin capas intermedias.'}</p></div><span class="pill ${real?'closed':'open'}">${real?'XI oficial publicado':'Previa'}</span></div><div class="matchday-hero"><div class="matchday-scoreboard"><div class="eyebrow">${real?'XI OFICIAL':'PRÓXIMO PARTIDO'}</div><h2>REAL MADRID <span>vs</span> ${esc(String(rival).toUpperCase())}</h2><h3 class="md-stage-title">${real?'El partido, de un vistazo':'Compara tu elección con el consenso'}</h3><p class="md-stage-copy">${real?'Primero, el once con la media combinada de las fuentes; después, la lectura del rendimiento y la comparación de pronósticos.':'Antes del partido basta con ver en qué coincidís y en qué os diferenciáis.'}</p></div></div>`}
function currentSeasonMatch(){
  const data=window.RMSeasonData,rival=String(safe(()=>predictionMatch?.rival,'')||'').trim().toLocaleLowerCase('es-ES');if(!data||!rival)return null;
  return (data.matches||[]).find(m=>String(m.label||'').trim().toLocaleLowerCase('es-ES')===rival)||null;
}
function fmtRating(v){return Number.isFinite(v)?Number(v).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}
function ratingTone(v){if(!Number.isFinite(v))return 'pending';if(v>=8)return 'elite';if(v>=7)return 'good';if(v<6.5)return 'low';return 'normal'}
function performanceData(){
  const data=window.RMSeasonData,match=currentSeasonMatch(),slotMap=officialSlots(),real=official(),slotDefs=safe(()=>slots,[])||[];if(!data||!match||!slotMap||!real||slotDefs.length!==11)return null;
  const starters=slotDefs.map(s=>{const name=slotMap[s[0]]||'';if(!name)return null;const entry=safe(()=>data.officialRatingEntry?.(match.id,name),null),minutes=safe(()=>data.minutes?.(match.id,name),null);return {key:s[0],label:s[1],x:s[2],y:s[3],name,display:display(name),rating:entry?.value??null,entry,minutes:Number.isFinite(minutes)?minutes:null}}).filter(Boolean);
  if(starters.length!==11)return null;
  const rated=starters.filter(x=>Number.isFinite(x.rating)),avg=rated.length?rated.reduce((sum,x)=>sum+x.rating,0)/rated.length:null,starterSet=new Set(starters.map(x=>canonical(x.name)));
  const bench=(safe(()=>players,[])||[]).map(p=>{if(starterSet.has(canonical(p.name)))return null;const minutes=safe(()=>data.minutes?.(match.id,p.name),null);if(!Number.isFinite(minutes)||minutes<=0)return null;const entry=safe(()=>data.officialRatingEntry?.(match.id,p.name),null);return {name:p.name,display:display(p.name),minutes,rating:entry?.value??null,entry}}).filter(Boolean).sort((a,b)=>b.minutes-a.minutes);
  return {data,match,starters,rated,avg,bench};
}
function pitchPlayer(row){const source=row.entry?.sourceCount===3?'3/3':row.entry?.status==='closed-partial'?`${row.entry.sourceCount}+SC`:row.entry?.status==='unrated'?'SC':'—';return `<div class="md-rating-player ${ratingTone(row.rating)}" style="left:${row.x}%;top:${row.y}%"><span>${esc(row.display)}</span><b>${fmtRating(row.rating)}</b><small>${row.minutes!==null?`${row.minutes}' · `:''}${esc(source)}</small></div>`}
function analysisHtml(p){
  const ordered=[...p.rated].sort((a,b)=>b.rating-a.rating||b.minutes-a.minutes),top=ordered.slice(0,3),low=[...ordered].sort((a,b)=>a.rating-b.rating||b.minutes-a.minutes).slice(0,3),complete=p.starters.filter(x=>x.entry?.complete).length;
  const topText=top.length?top.map((x,i)=>`${i?i===top.length-1?' y ':', ':''}${display(x.name)} (${fmtRating(x.rating)})`).join(''): 'Sin notas cerradas';
  const lowText=low.length?low.map((x,i)=>`${i?i===low.length-1?' y ':', ':''}${display(x.name)} (${fmtRating(x.rating)})`).join(''): 'Sin notas cerradas';
  return `<article class="md-match-analysis"><div class="md-analysis-head"><div><span class="md-label">ANÁLISIS DEL PARTIDO</span><h3>Lectura de las notas</h3></div><div class="md-analysis-average"><small>Media XI</small><b>${fmtRating(p.avg)}</b></div></div><p class="md-analysis-intro">Análisis objetivo a partir de las valoraciones combinadas de SofaScore, FotMob y StatMuse. No añade acciones de partido que no estén registradas.</p><div class="md-analysis-points"><div><span>★</span><p><b>Mejores medias.</b> ${esc(topText)}.</p></div><div><span>↘</span><p><b>Zona más baja.</b> ${esc(lowText)}.</p></div><div><span>✓</span><p><b>Cobertura.</b> ${complete}/11 titulares tienen las tres fuentes cerradas${complete===11?' y la comparación del XI es completa.':'.'}</p></div></div></article>`
}
function subsHtml(p){if(!p.bench.length)return '';return `<details class="md-used-subs"><summary><span>SUPLENTES UTILIZADOS</span><b>${p.bench.length}</b><strong>+</strong></summary><div class="md-sub-list">${p.bench.map(x=>`<div><span><b>${esc(x.display)}</b><small>${x.minutes}'${x.entry?.complete?' · 3/3':x.entry?.status==='closed-partial'?` · ${x.entry.sourceCount}+SC`:''}</small></span><strong class="${ratingTone(x.rating)}">${fmtRating(x.rating)}</strong></div>`).join('')}</div></details>`}
function performanceHtml(){
  const p=performanceData();if(!official())return '';
  if(!p)return `<section class="card md-performance md-performance-wait"><div><span class="md-label">ALINEACIÓN · NOTAS MEDIAS</span><h2>Notas en revisión</h2><p>El XI oficial ya está publicado. Esta tarjeta se completará automáticamente cuando las valoraciones del partido estén cerradas en la base de temporada.</p></div></section>`;
  return `<section class="card md-performance"><div class="section-head md-performance-title" style="margin-top:0"><div><span class="md-label">XI OFICIAL · NOTAS MEDIAS</span><h2>Alineación y rendimiento</h2><p>Nota media del partido: media aritmética de SofaScore + FotMob + StatMuse. El minuto aparece debajo de cada jugador.</p></div><div class="md-team-rating"><span>MEDIA DEL XI</span><b>${fmtRating(p.avg)}</b><small>${p.starters.filter(x=>x.entry?.complete).length}/11 con 3/3</small></div></div><div class="md-performance-grid"><div class="md-rating-pitch" aria-label="Alineación oficial con notas medias"><div class="md-pitch-half"></div><div class="md-pitch-circle"></div>${p.starters.map(pitchPlayer).join('')}</div>${analysisHtml(p)}</div>${subsHtml(p)}</section>`
}
function diffBlock(user,community){if(!valid(user)||!valid(community))return '';const A=new Set(values(user).map(canonical)),B=new Set(values(community).map(canonical)),same=values(user).filter(n=>B.has(canonical(n))),onlyMine=values(user).filter(n=>!B.has(canonical(n))),onlyCommunity=values(community).filter(n=>!A.has(canonical(n)));return `<section class="card md-differences"><div class="section-head" style="margin-top:0"><div><span class="md-label">TU XI VS COMUNIDAD</span><h2>${same.length}/11 coincidencias</h2><p>Las diferencias se leen por jugador, no por posición exacta.</p></div></div><div class="md-diff-grid"><div><span>Solo en tu XI</span>${chips(Object.fromEntries(onlyMine.map((n,i)=>[i,n])),'miss')}</div><div><span>Solo comunidad</span>${chips(Object.fromEntries(onlyCommunity.map((n,i)=>[i,n])),'surprise')}</div></div></section>`}
function render(){const section=ensure();if(!section)return;let root=document.getElementById('matchdayDynamic');if(!root){root=document.createElement('div');root.id='matchdayDynamic';section.appendChild(root)}const user=mine(),community=communityXi(),real=official();root.innerHTML=`${hero()}${performanceHtml()}<div class="md-xi-grid">${card('TU PREDICCIÓN','Tu XI',user,'Ver mi predicción','prediccion')}${card('COMUNIDAD','XI más votado',community,'Ver comunidad','comunidad')}${card('XI OFICIAL','Once confirmado',real,null,null)}</div>${diffBlock(user,community)}${real?`<section class="card md-community"><div class="section-head" style="margin-top:0"><div><span class="md-label">RESULTADO DE LA PREDICCIÓN</span><h2>Tu XI y la comunidad frente al oficial</h2><p>Tú: <b>${score(user)??'—'}/11</b> · Comunidad: <b>${score(community)??'—'}/11</b>.</p></div></div></section>`:''}`;root.querySelectorAll('[data-md-go]').forEach(b=>b.addEventListener('click',()=>safe(()=>showSection(b.dataset.mdGo))));}
function loadCommunity(){if(window.RMCommunityData){communityData=window.RMCommunityData;render();return}safe(()=>window.RMCommunityApi?.refresh?.())}
function install(){if(installed)return;const section=ensure();if(!section){setTimeout(install,100);return}installed=true;render();const base=showSection;showSection=function(id){base(id);if(id==='partido'){loadCommunity();setTimeout(render,0)}};document.addEventListener('rm-community-updated',e=>{communityData=e.detail||window.RMCommunityData||communityData;render()});document.addEventListener('rm-local-prediction-updated',render);document.addEventListener('rm-ranking-official-ready',render);document.addEventListener('rm-season-data-ready',()=>setTimeout(render,20));document.addEventListener('rm-season-extension-ready',()=>setTimeout(render,20));window.RMMatchdayCenter=Object.freeze({render,refresh:loadCommunity,performance:performanceData})}
install();
})();