(()=>{
const POLL_SECTION=['encuestas','☑','Encuestas','Encuestas y predicciones','Vota, compara tu opinión con la afición y sigue los debates del próximo partido.'];
let pollCache=null,pollInstalled=false;
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const apiUrl=params=>{const u=new URL('https://vvltmdedwgjtvlcmindn.supabase.co/functions/v1/polls');Object.entries(params||{}).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v))});return u.href};
const participantId=()=>window.RMCommunityApi?.participantId?.()||localStorage.getItem('rm_community_participant_id')||'';
function css(){if(document.getElementById('rmPollCss'))return;const s=document.createElement('style');s.id='rmPollCss';s.textContent=`
#encuestas .poll-hero{display:grid;grid-template-columns:1.35fr .65fr;gap:16px;margin-bottom:16px}.poll-feature{position:relative;overflow:hidden;min-height:220px}.poll-feature:after{content:'?';position:absolute;right:14px;bottom:-55px;font-size:220px;font-weight:1000;color:rgba(255,255,255,.025)}.poll-kicker{font-size:11px;font-weight:900;letter-spacing:.13em;color:var(--gold);text-transform:uppercase}.poll-feature h2{font-size:clamp(25px,4vw,38px);line-height:1.05;margin:10px 0 8px;max-width:760px}.poll-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.poll-card{display:flex;flex-direction:column;gap:13px}.poll-card h3{margin:0;font-size:19px}.poll-card p{margin:0}.poll-options{display:grid;gap:9px}.poll-option{position:relative;width:100%;border:1px solid var(--line);background:#091522;color:var(--text);border-radius:14px;padding:12px 13px;text-align:left;overflow:hidden}.poll-option:hover{border-color:#44658c}.poll-option.selected{border-color:var(--gold);box-shadow:0 0 0 1px rgba(216,180,74,.2)}.poll-option:disabled{opacity:.9}.poll-option-fill{position:absolute;inset:0 auto 0 0;background:rgba(93,167,255,.12);pointer-events:none}.poll-option-main{position:relative;display:flex;justify-content:space-between;gap:12px;align-items:center;z-index:1}.poll-option-main b{font-size:13px}.poll-option-main span{font-weight:900;color:#bdd8fb}.poll-card-footer{display:flex;justify-content:space-between;gap:10px;align-items:center;color:var(--muted);font-size:11px}.poll-summary{display:grid;gap:10px}.poll-summary-row{display:flex;justify-content:space-between;gap:10px;border-bottom:1px solid var(--line);padding-bottom:9px}.poll-summary-row:last-child{border:0}.poll-summary-row span{color:var(--muted)}.poll-stat{font-size:34px;font-weight:950;letter-spacing:-.05em}.poll-empty{padding:24px;text-align:center;color:var(--muted)}.poll-history{display:grid;gap:10px}.poll-history-item{display:grid;grid-template-columns:1fr auto;gap:10px;border-top:1px solid var(--line);padding-top:11px}.poll-history-item:first-child{border-top:0;padding-top:0}.poll-history-item small{color:var(--muted)}.poll-nav-badge{margin-left:auto;font-size:9px;padding:3px 6px;border-radius:999px;background:rgba(216,180,74,.13);color:var(--gold)}
@media(max-width:900px){#encuestas .poll-hero,.poll-grid{grid-template-columns:1fr}}@media(max-width:520px){.poll-option{padding:11px}.poll-feature h2{font-size:27px}}
`;document.head.appendChild(s)}
function ensureSection(){if(document.getElementById('encuestas'))return;const community=document.getElementById('comunidad'),main=document.querySelector('main');if(!main)return;const section=document.createElement('section');section.className='section';section.id='encuestas';section.innerHTML=`<div class="section-head"><div><h2>La voz de la afición</h2><p>Encuestas rápidas, debates y predicciones alrededor del próximo partido.</p></div><button class="btn" type="button" onclick="RMPolls.refresh()">Actualizar</button></div><div id="pollRoot"><div class="card poll-empty">Cargando encuestas…</div></div>`;main.insertBefore(section,community||null)}
function ensureMeta(){if(typeof sections==='undefined')return false;if(!sections.some(s=>s[0]==='encuestas')){const i=sections.findIndex(s=>s[0]==='comunidad');sections.splice(i<0?sections.length:i,0,POLL_SECTION)}return true}
function ensureNav(){const desk=document.getElementById('navDesktop');if(desk&&!desk.querySelector('[data-section="encuestas"]')){const communityBtn=desk.querySelector('[data-section="comunidad"]'),group=communityBtn?.closest('.ux-nav-group'),b=document.createElement('button');b.dataset.section='encuestas';b.onclick=()=>showSection('encuestas');b.innerHTML='<span>☑</span><em>Encuestas</em><small class="poll-nav-badge">NUEVO</small>';if(group)group.appendChild(b);else desk.appendChild(b)}const sheet=document.getElementById('uxMoreSheet');if(sheet&&!sheet.querySelector('[data-section="encuestas"]')){const groups=sheet.querySelector('.ux-sheet-groups');if(groups){let sec=[...groups.querySelectorAll('section')].find(s=>s.querySelector('h3')?.textContent==='Comunidad');if(!sec){sec=document.createElement('section');sec.innerHTML='<h3>Comunidad</h3><div></div>';groups.appendChild(sec)}const b=document.createElement('button');b.dataset.section='encuestas';b.onclick=()=>{showSection('encuestas');window.closeUxMore?.()};b.innerHTML='<span>☑</span><b>Encuestas</b><small>Vota y compara tu opinión con la afición.</small>';sec.querySelector('div')?.appendChild(b)}}}
function fmtClose(v){const diff=new Date(v).getTime()-Date.now();if(diff<=0)return 'Cerrada';const h=Math.floor(diff/36e5);if(h<24)return `Cierra en ${h} h`;const days=Math.ceil(h/24);return `Cierra en ${days} día${days===1?'':'s'}`}
function pollCard(p,featured=false){const reveal=p.totalVotes>0||p.myVote||p.closed;return `<article class="card poll-card ${featured?'poll-feature':''}"><div><div class="poll-kicker">${featured?'Encuesta del día':p.category==='match'?'Predicción del partido':'Debate de la afición'}</div><h3>${esc(p.question)}</h3>${p.subtitle?`<p class="muted">${esc(p.subtitle)}</p>`:''}</div><div class="poll-options">${(p.options||[]).map(o=>`<button class="poll-option ${p.myVote===o.key?'selected':''}" type="button" ${p.closed?'disabled':''} onclick="RMPolls.vote('${esc(p.id)}','${esc(o.key)}')">${reveal?`<i class="poll-option-fill" style="width:${o.percentage}%"></i>`:''}<span class="poll-option-main"><b>${esc(o.label)}</b><span>${reveal?`${o.percentage}%`:p.myVote===o.key?'✓':''}</span></span></button>`).join('')}</div><div class="poll-card-footer"><span>${p.totalVotes||0} voto${p.totalVotes===1?'':'s'}${p.myVote?' · tu voto está guardado':''}</span><b>${fmtClose(p.closes_at)}</b></div></article>`}
function render(data){pollCache=data;const root=document.getElementById('pollRoot');if(!root)return;const polls=data?.polls||[],featured=polls.find(p=>p.featured&&!p.closed)||polls.find(p=>!p.closed),active=polls.filter(p=>!p.closed&&p.id!==featured?.id),closed=polls.filter(p=>p.closed),mine=polls.filter(p=>p.myVote).length,totalVotes=polls.reduce((n,p)=>n+(p.totalVotes||0),0),xp=mine*10;root.innerHTML=`${featured?`<div class="poll-hero">${pollCard(featured,true)}<aside class="card poll-summary"><div><div class="eyebrow">TU ACTIVIDAD</div><div class="poll-stat">${xp} XP</div><p class="muted">10 XP por cada encuesta en la que participas.</p></div><div class="poll-summary-row"><span>Encuestas respondidas</span><b>${mine}</b></div><div class="poll-summary-row"><span>Votos de la comunidad</span><b>${totalVotes}</b></div><div class="poll-summary-row"><span>Encuestas abiertas</span><b>${polls.filter(p=>!p.closed).length}</b></div><button class="btn primary" type="button" onclick="showSection('prediccion')">Hacer mi XI →</button></aside></div>`:''}<div class="section-head"><div><h2>Más encuestas abiertas</h2><p>Puedes cambiar tu voto mientras la encuesta siga abierta.</p></div></div>${active.length?`<div class="poll-grid">${active.map(p=>pollCard(p)).join('')}</div>`:'<div class="card poll-empty">No hay más encuestas abiertas ahora mismo.</div>'}<div class="section-head"><div><h2>Histórico</h2><p>Resultados de encuestas que ya han finalizado.</p></div></div><div class="card poll-history">${closed.length?closed.slice(0,8).map(p=>{const winner=[...(p.options||[])].sort((a,b)=>b.count-a.count)[0];return `<div class="poll-history-item"><div><b>${esc(p.question)}</b><small>${winner?`Ganó: ${esc(winner.label)} · ${winner.percentage}%`:'Sin votos'}</small></div><strong>${p.totalVotes||0} votos</strong></div>`}).join(''):'<div class="muted">Todavía no hay encuestas cerradas.</div>'}</div>`}
async function load(force=false){if(pollCache&&!force){render(pollCache);return pollCache}const root=document.getElementById('pollRoot');if(root)root.innerHTML='<div class="card poll-empty">Cargando encuestas…</div>';try{const r=await fetch(apiUrl({participantId:participantId()}),{headers:{accept:'application/json'}}),d=await r.json();if(!r.ok)throw new Error(d.error||`Error ${r.status}`);render(d);return d}catch(e){if(root)root.innerHTML=`<div class="card poll-empty"><b>No se pudieron cargar las encuestas.</b><br>${esc(e.message||'Error de conexión')}</div>`;return null}}
async function vote(pollId,optionKey){try{const r=await fetch(apiUrl(),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({participantId:participantId(),pollId,optionKey})}),d=await r.json();if(!r.ok)throw new Error(d.error||`Error ${r.status}`);if(typeof toast==='function')toast('Voto guardado ✓');pollCache=null;await load(true)}catch(e){if(typeof toast==='function'){toast(e.message||'No se pudo guardar el voto')}else{alert(e.message||'No se pudo guardar el voto')}}}
function install(){if(pollInstalled)return;if(typeof sections==='undefined'||typeof showSection!=='function'||!document.querySelector('main')){setTimeout(install,80);return}pollInstalled=true;css();ensureMeta();ensureSection();const base=showSection;showSection=function(id){base(id);if(id==='encuestas')load();setTimeout(ensureNav,0)};window.RMPolls=Object.freeze({refresh:()=>load(true),vote,open:()=>showSection('encuestas')});ensureNav();[100,500,1200,2600,5000].forEach(ms=>setTimeout(ensureNav,ms));const wanted=new URLSearchParams(location.search).get('section');if(wanted==='encuestas')setTimeout(()=>showSection('encuestas'),100);document.addEventListener('rm-modules-ready',ensureNav)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();