(()=>{
let ppPos='ALL',ppMin=0,ppSort='power';
function season(){return window.RMSeasonData}
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function canon(name){return season()?.canonical?.(name)||name}
function metric(p){return typeof metricFor==='function'?metricFor(p):null}
function rating(p){const m=metric(p);return typeof currentRating==='function'?currentRating(m):null}
function officialPower(p){const target=canon(p.name),row=(window.RMPowerMigration?.official||[]).find(x=>canon(x.name)===target);if(Number.isFinite(row?.power))return row.power;const m=metric(p),r=rating(p);return m&&Number.isFinite(r)?r*(.75+.25*Math.min(m.minutes,450)/450):null}
function sd(vals){if(vals.length<2)return null;const avg=vals.reduce((a,b)=>a+b,0)/vals.length;return Math.sqrt(vals.reduce((s,v)=>s+(v-avg)**2,0)/vals.length)}
function rowFor(p){
  const m=metric(p),r=rating(p),power=officialPower(p),recent=season()?.recentRating?.(p.name,3)||null,delta=season()?.ratingDelta?.(p.name)||null,series=season()?.ratingSeries?.(p.name)||[],vals=series.map(x=>x.entry?.value).filter(Number.isFinite),stability=sd(vals),sample=Math.min(m?.minutes||0,450)/450;
  return {p,m,r,power,recent,delta,series,stability,sample,penalty:Number.isFinite(r)&&Number.isFinite(power)?r-power:null};
}
function allRows(){return players.map(rowFor).filter(x=>Number.isFinite(x.power)).sort((a,b)=>b.power-a.power||b.r-a.r||(a.p.short||a.p.name).localeCompare(b.p.short||b.p.name,'es')).map((x,i)=>({...x,rank:i+1}))}
function sampleLabel(row){const min=row.m?.minutes||0;if(min>=450)return 'Completa';if(min>=270)return 'Alta';if(min>=180)return 'Media';if(min>=90)return 'En desarrollo';return 'Corta'}
function zone(row){if((row.m?.minutes||0)<90)return ['MUESTRA CORTA','short'];if(row.power>=7.5)return ['ÉLITE','elite'];if(row.power>=7)return ['MUY ALTO','very'];if(row.power>=6.5)return ['ALTO','high'];return ['SEGUIMIENTO','watch']}
function stabilityLabel(row){if(row.stability===null)return 'Sin muestra';if(row.stability<.35)return 'Muy estable';if(row.stability<.65)return 'Estable';if(row.stability<1)return 'Variable';return 'Volátil'}
function trend(row){const d=row.delta?.delta;if(!Number.isFinite(d))return {label:'Sin tendencia',cls:'flat'};if(d>=.25)return {label:`▲ +${d.toFixed(2)}`,cls:'up'};if(d<=-.25)return {label:`▼ ${d.toFixed(2)}`,cls:'down'};return {label:`• ${d>=0?'+':''}${d.toFixed(2)}`,cls:'flat'}}
function spark(row){const vals=row.series.map(x=>x.entry?.value).filter(Number.isFinite);if(vals.length<2)return '<span class="pwp-no-spark">—</span>';const W=116,H=34,min=Math.min(...vals,5.5),max=Math.max(...vals,9),range=Math.max(.5,max-min),pts=vals.map((v,i)=>`${(i/(vals.length-1)*W).toFixed(1)},${(H-(v-min)/range*H).toFixed(1)}`).join(' ');return `<svg class="pwp-spark" viewBox="0 0 ${W} ${H}" role="img" aria-label="Evolución reciente"><polyline points="${pts}" fill="none" vector-effect="non-scaling-stroke"/></svg>`}
function filtered(){let rows=allRows().filter(x=>(ppPos==='ALL'||x.p.pos===ppPos)&&(x.m?.minutes||0)>=ppMin);const sorter={power:(a,b)=>b.power-a.power,form:(a,b)=>(b.recent?.value??-Infinity)-(a.recent?.value??-Infinity)||b.power-a.power,rating:(a,b)=>b.r-a.r||b.power-a.power,minutes:(a,b)=>(b.m?.minutes||0)-(a.m?.minutes||0)||b.power-a.power,stability:(a,b)=>(a.stability??Infinity)-(b.stability??Infinity)||b.power-a.power}[ppSort];return rows.sort(sorter)}
function closestText(rows){if(rows.length<2)return 'Sin rival comparable';const gap=rows[0].power-rows[1].power;return gap<.2?'Liderato muy abierto':gap<.5?'Ventaja corta':'Liderazgo claro'}
function rowHtml(row){const z=zone(row),t=trend(row),sample=Math.round(row.sample*100);return `<article class="pwp-row" tabindex="0" onclick="RMPowerPro.open('${row.p.name.replace(/'/g,"\\'")}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();RMPowerPro.open('${row.p.name.replace(/'/g,"\\'")}')}"><div class="pwp-rank"><b>#${row.rank}</b><span class="${z[1]}">${z[0]}</span></div><div class="pwp-player"><strong>${esc(row.p.short||row.p.name)}</strong><small>${esc(row.p.role||row.p.pos)}</small><div class="pwp-sample"><i style="width:${sample}%"></i></div><em>${sample}% muestra · ${sampleLabel(row)}</em></div><div class="pwp-main"><b>${row.power.toFixed(2)}</b><small>Power RM</small></div><div class="pwp-stat"><b>${row.r?.toFixed(2)??'—'}</b><small>Media</small></div><div class="pwp-stat"><b>${row.m?.minutes??'—'}</b><small>Min</small></div><div class="pwp-stat"><b>${row.recent?.value?.toFixed(2)??'—'}</b><small>Forma · ${row.recent?.n||0}</small></div><div class="pwp-trend ${t.cls}"><b>${t.label}</b><small>Última variación</small></div><div class="pwp-stability"><b>${stabilityLabel(row)}</b><small>${row.stability===null?'—':`σ ${row.stability.toFixed(2)} · ${row.series.length} notas`}</small></div><div class="pwp-spark-wrap">${spark(row)}</div><button class="pwp-radar" onclick="event.stopPropagation();RMPowerPro.radar('${row.p.name.replace(/'/g,"\\'")}')">Radar</button></article>`}
function render(){
  const section=document.getElementById('power');if(!section||!season()||typeof players==='undefined')return;const all=allRows(),rows=filtered(),leader=rows[0]||null,second=rows[1]||null,bestForm=[...rows].filter(x=>x.recent?.n>=2).sort((a,b)=>b.recent.value-a.recent.value)[0]||null,stable=[...rows].filter(x=>x.stability!==null&&x.series.length>=3).sort((a,b)=>a.stability-b.stability)[0]||null,gap=leader&&second?leader.power-second.power:null;
  section.innerHTML=`<div class="section-head"><div><div class="eyebrow">POWER RM PRO</div><h2>Power RM</h2><p>Rendimiento actual ajustado por muestra. La fórmula no cambia: ahora ves también cuánto puedes confiar en cada cifra.</p></div><button class="btn" onclick="showSection('evolucion')">Ver evolución</button></div>
  <div class="pwp-hero"><div class="pwp-leader"><span>LÍDER DEL FILTRO</span><h2>${leader?esc(leader.p.short||leader.p.name):'—'}</h2><strong>${leader?leader.power.toFixed(2):'—'}</strong><small>${leader?`Media ${leader.r.toFixed(2)} · ${leader.m.minutes} min · ${Math.round(leader.sample*100)}% muestra`:'Sin jugadores con este filtro'}</small></div><div class="pwp-hero-grid"><div><span>Distancia al 2.º</span><b>${gap===null?'—':gap.toFixed(2)}</b><small>${closestText(rows)}</small></div><div><span>Mejor forma</span><b>${bestForm?esc(bestForm.p.short||bestForm.p.name):'—'}</b><small>${bestForm?`${bestForm.recent.value.toFixed(2)} · ${bestForm.recent.n} notas`:'Sin muestra suficiente'}</small></div><div><span>Más estable</span><b>${stable?esc(stable.p.short||stable.p.name):'—'}</b><small>${stable?`σ ${stable.stability.toFixed(2)} · ${stable.series.length} notas`:'Necesita 3 notas'}</small></div></div></div>
  <div class="pwp-podium">${rows.slice(0,3).map((r,i)=>`<button onclick="RMPowerPro.open('${r.p.name.replace(/'/g,"\\'")}')"><span>#${r.rank}</span><b>${esc(r.p.short||r.p.name)}</b><strong>${r.power.toFixed(2)}</strong><small>${sampleLabel(r)} · ${Math.round(r.sample*100)}%</small></button>`).join('')}</div>
  <div class="card pwp-controls"><div><span>POSICIÓN</span><div>${[['ALL','Todos'],['POR','POR'],['DEF','DEF'],['MED','MED'],['ATA','ATA']].map(([v,l])=>`<button class="${ppPos===v?'active':''}" onclick="RMPowerPro.position('${v}')">${l}</button>`).join('')}</div></div><div><span>MUESTRA MÍNIMA</span><select class="select" onchange="RMPowerPro.minimum(Number(this.value))"><option value="0" ${ppMin===0?'selected':''}>Todos</option><option value="90" ${ppMin===90?'selected':''}>90+ min</option><option value="180" ${ppMin===180?'selected':''}>180+ min</option><option value="270" ${ppMin===270?'selected':''}>270+ min</option></select></div><div><span>ORDENAR</span><select class="select" onchange="RMPowerPro.sort(this.value)"><option value="power" ${ppSort==='power'?'selected':''}>Power RM</option><option value="form" ${ppSort==='form'?'selected':''}>Forma reciente</option><option value="rating" ${ppSort==='rating'?'selected':''}>Media</option><option value="minutes" ${ppSort==='minutes'?'selected':''}>Minutos</option><option value="stability" ${ppSort==='stability'?'selected':''}>Estabilidad</option></select></div></div>
  <div class="card pwp-explain"><div><div class="eyebrow">CÓMO LEER POWER</div><h3>La muestra puede cambiar la interpretación, no la nota original</h3><p>Power RM = media × (0,75 + 0,25 × muestra). La muestra llega al 100% a los 450 minutos. Un jugador con pocos minutos conserva su media, pero su Power se modera hasta que acumula evidencia.</p></div><div><b>${all.length}</b><span>jugadores con Power</span><small>SC conserva minutos pero nunca se convierte en una nota 0.</small></div></div>
  <div class="pwp-list-head"><span>Jugador</span><span>Power</span><span>Media</span><span>Min</span><span>Forma</span><span>Tendencia</span><span>Estabilidad</span><span>Curva</span><span></span></div><div class="pwp-list">${rows.length?rows.map(rowHtml).join(''):'<div class="pwp-empty">No hay jugadores que cumplan este filtro.</div>'}</div>
  <div class="pwp-integrity"><b>Power no sustituye la jerarquía ni el contexto táctico.</b><span>Sirve para comparar rendimiento y respaldo de muestra. Para decidir entre dos jugadores concretos, abre Radar; para ver el cambio jornada a jornada, usa Evolución.</span></div>`;
  document.body.classList.add('power-pro-ready');
}
function openPlayer(name){if(window.RMPlayerExperience?.open)window.RMPlayerExperience.open(name);else if(typeof openPlayerHub==='function')openPlayerHub(name)}
function radar(name){const leader=allRows()[0]?.p.name;if(!leader||leader===name){if(typeof showSection==='function')showSection('radar');return}if(typeof showSection==='function')showSection('radar');setTimeout(()=>window.RMDecisionRadar?.set?.(name,leader),40)}
window.RMPowerPro=Object.freeze({render,open:openPlayer,radar,position:v=>{ppPos=v;render()},minimum:v=>{ppMin=Number(v)||0;render()},sort:v=>{ppSort=v;render()},rows:allRows});
['rm-power-official-ready','rm-ranking-official-ready','rm-season-data-ready'].forEach(name=>document.addEventListener(name,()=>setTimeout(render,0)));
setTimeout(render,0);
})();