(()=>{
let ppPos='ALL',ppMin=0,ppSort='power';
function season(){return window.RMSeasonData}
function analysis(){return window.RMAnalysisContext||null}
function context(){return analysis()?.state?.()||{competition:'ALL',horizon:'ALL'}}
function contextMatches(){return analysis()?.matches?.()||season()?.matches||[]}
function contextLabel(){return analysis()?.label?.()||`${contextMatches().length} jornadas`}
function contextIsFull(){const c=context();return c.competition==='ALL'&&c.horizon==='ALL'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function canon(name){return season()?.canonical?.(name)||name}
function windowFor(p){
  const sd=season(),series=[];let minutes=0,ratedMinutes=0,points=0,lastPlayed=null;
  for(const match of contextMatches()){
    const min=Number(sd?.minutes?.(match.id,p.name))||0;if(min<=0)continue;minutes+=min;lastPlayed=match;
    const entry=sd?.officialRatingEntry?.(match.id,p.name);if(entry&&Number.isFinite(entry.value)){ratedMinutes+=min;points+=entry.value*min/90;series.push({match,entry})}
  }
  const vals=series.map(x=>x.entry.value),r=ratedMinutes?points*90/ratedMinutes:null,recentVals=vals.slice(-3),recent=recentVals.length?{value:recentVals.reduce((a,b)=>a+b,0)/recentVals.length,n:recentVals.length}:null,delta=vals.length>=2?{delta:vals.at(-1)-vals.at(-2)}:null,sample=Math.min(minutes,450)/450,power=Number.isFinite(r)?r*(.75+.25*sample):null;
  return {m:{minutes,ratedMinutes,points,minPerPoint:points?ratedMinutes/points:null},r,recent,delta,series,lastPlayed,sample,power};
}
function officialPower(p,w){const target=canon(p.name),row=contextIsFull()?(window.RMPowerMigration?.official||[]).find(x=>canon(x.name)===target):null;if(Number.isFinite(row?.power))return row.power;return w.power}
function sd(vals){if(vals.length<2)return null;const avg=vals.reduce((a,b)=>a+b,0)/vals.length;return Math.sqrt(vals.reduce((s,v)=>s+(v-avg)**2,0)/vals.length)}
function rowFor(p){const w=windowFor(p),m=w.m,r=w.r,power=officialPower(p,w),recent=w.recent,delta=w.delta,series=w.series,vals=series.map(x=>x.entry?.value).filter(Number.isFinite),stability=sd(vals),sample=w.sample;return {p,m,r,power,recent,delta,series,lastPlayed:w.lastPlayed,stability,sample,penalty:Number.isFinite(r)&&Number.isFinite(power)?r-power:null}}
function allRows(){return players.map(rowFor).filter(x=>Number.isFinite(x.power)).sort((a,b)=>b.power-a.power||b.r-a.r||(a.p.short||a.p.name).localeCompare(b.p.short||b.p.name,'es')).map((x,i)=>({...x,rank:i+1}))}
function sampleLabel(row){const min=row.m?.minutes||0;if(min>=450)return 'Completa';if(min>=270)return 'Alta';if(min>=180)return 'Media';if(min>=90)return 'En desarrollo';return 'Corta'}
function zone(row){if((row.m?.minutes||0)<90)return ['MUESTRA CORTA','short'];if(row.power>=7.5)return ['ÉLITE','elite'];if(row.power>=7)return ['MUY ALTO','very'];if(row.power>=6.5)return ['ALTO','high'];return ['SEGUIMIENTO','watch']}
function stabilityLabel(row){if(row.stability===null)return 'Sin muestra';if(row.stability<.35)return 'Muy estable';if(row.stability<.65)return 'Estable';if(row.stability<1)return 'Variable';return 'Volátil'}
function trend(row){const d=row.delta?.delta;if(!Number.isFinite(d))return {label:'Sin tendencia',cls:'flat'};if(d>=.25)return {label:`▲ +${d.toFixed(2)}`,cls:'up'};if(d<=-.25)return {label:`▼ ${d.toFixed(2)}`,cls:'down'};return {label:`• ${d>=0?'+':''}${d.toFixed(2)}`,cls:'flat'}}
function spark(row){
  const ms=contextMatches(),points=row.series.map(x=>({value:x.entry?.value,index:ms.findIndex(m=>m.id===x.match.id)})).filter(x=>Number.isFinite(x.value)&&x.index>=0);
  if(points.length<2)return '<span class="pwp-no-spark">—</span>';
  const W=116,H=34,vals=points.map(x=>x.value),min=Math.min(...vals,5.5),max=Math.max(...vals,9),range=Math.max(.5,max-min),span=Math.max(1,ms.length-1);
  const pts=points.map(p=>`${(p.index/span*W).toFixed(1)},${(H-(p.value-min)/range*H).toFixed(1)}`).join(' ');
  return `<svg class="pwp-spark" viewBox="0 0 ${W} ${H}" role="img" aria-label="Evolución reciente"><polyline points="${pts}" fill="none" vector-effect="non-scaling-stroke"/></svg>`
}
function sortConfig(){return {
  power:{head:'Power',label:'Power RM',value:r=>r.power,format:r=>Number.isFinite(r.power)?r.power.toFixed(2):'—',asc:false},
  form:{head:'Forma',label:r=>`Forma · ${r.recent?.n||0} apar.`,value:r=>r.recent?.value,format:r=>Number.isFinite(r.recent?.value)?r.recent.value.toFixed(2):'—',asc:false},
  rating:{head:'Media',label:'Media oficial',value:r=>r.r,format:r=>Number.isFinite(r.r)?r.r.toFixed(2):'—',asc:false},
  minutes:{head:'Minutos',label:'Minutos jugados',value:r=>r.m?.minutes,format:r=>Number.isFinite(r.m?.minutes)?String(r.m.minutes):'—',asc:false},
  stability:{head:'Estabilidad',label:'Estabilidad · σ',value:r=>r.stability,format:r=>Number.isFinite(r.stability)?`σ ${r.stability.toFixed(2)}`:'—',asc:true}
}[ppSort]||null}
function metricValue(row){return sortConfig()?.value(row)}
function powerFiltered(){return allRows().filter(x=>(ppPos==='ALL'||x.p.pos===ppPos)&&(x.m?.minutes||0)>=ppMin)}
function visibleRows(){const rows=powerFiltered(),cfg=sortConfig();return [...rows].sort((a,b)=>{const av=cfg.value(a),bv=cfg.value(b),af=Number.isFinite(av),bf=Number.isFinite(bv);if(af!==bf)return af?-1:1;if(!af&&!bf)return b.power-a.power;const diff=cfg.asc?av-bv:bv-av;return diff||b.power-a.power||b.r-a.r}).map((row,index)=>({...row,sortRank:Number.isFinite(cfg.value(row))?index+1:null}))}
function closestText(rows){if(rows.length<2)return 'Sin rival comparable';const gap=rows[0].power-rows[1].power;return gap<.2?'Liderato muy abierto':gap<.5?'Ventaja corta':'Liderazgo claro'}
function competitionOptions(){const c=context(),items=analysis()?.competitions?.()||[];return `<option value="ALL" ${c.competition==='ALL'?'selected':''}>Todas las competiciones</option>${items.map(x=>`<option value="${esc(x)}" ${c.competition===x?'selected':''}>${esc(x)}</option>`).join('')}`}
function contextControls(){const c=context();return `<div class="card pwp-controls"><div><span>CONTEXTO COMPARTIDO</span><small>${esc(contextLabel())}</small></div><div><span>COMPETICIÓN</span><select class="select" onchange="RMAnalysisContext?.set?.({competition:this.value},'power')">${competitionOptions()}</select></div><div><span>PERIODO</span><select class="select" onchange="RMAnalysisContext?.set?.({horizon:this.value},'power')"><option value="ALL" ${c.horizon==='ALL'?'selected':''}>Todo el periodo</option><option value="5" ${c.horizon==='5'?'selected':''}>Últimos 5</option><option value="3" ${c.horizon==='3'?'selected':''}>Últimos 3</option><option value="1" ${c.horizon==='1'?'selected':''}>Último partido</option></select></div></div>`}
function rankBadge(row){if(ppSort==='power')return zone(row);if(ppSort==='form')return [row.recent?.n>=3?'FORMA 3':row.recent?.n===2?'FORMA 2':row.recent?.n===1?'FORMA 1':'SIN FORMA',row.recent?.n>=3?'very':row.recent?.n===2?'high':'short'];if(ppSort==='rating')return ['MEDIA','high'];if(ppSort==='minutes')return ['MINUTOS','high'];const label=stabilityLabel(row).toUpperCase();return [label,row.stability===null?'short':row.stability<.65?'elite':row.stability<1?'high':'watch']}
function selectedMetric(row){const cfg=sortConfig(),label=typeof cfg.label==='function'?cfg.label(row):cfg.label,secondary=ppSort==='power'?null:`Power #${row.rank} · ${row.power.toFixed(2)}`;return {rank:row.sortRank??'—',value:cfg.format(row),label,secondary}}
function rowHtml(row){const z=rankBadge(row),t=trend(row),sample=Math.round(row.sample*100),view=selectedMetric(row),last=row.lastPlayed?.label||row.lastPlayed?.short||'—';return `<article class="pwp-row" tabindex="0" onclick="RMPowerPro.open('${row.p.name.replace(/'/g,"\\'")}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();RMPowerPro.open('${row.p.name.replace(/'/g,"\\'")}')}"><div class="pwp-rank"><b>#${view.rank}</b><span class="${z[1]}">${z[0]}</span></div><div class="pwp-player"><strong>${esc(row.p.short||row.p.name)}</strong><small>${esc(row.p.role||row.p.pos)}</small><div class="pwp-sample"><i style="width:${sample}%"></i></div><em>${sample}% muestra · ${sampleLabel(row)} · Último: ${esc(last)}</em></div><div class="pwp-main"><b>${view.value}</b><small>${esc(view.label)}</small>${view.secondary?`<small>${esc(view.secondary)}</small>`:''}</div><div class="pwp-stat"><b>${row.r?.toFixed(2)??'—'}</b><small>Media</small></div><div class="pwp-stat"><b>${row.m?.minutes??'—'}</b><small>Min</small></div><div class="pwp-stat"><b>${row.recent?.value?.toFixed(2)??'—'}</b><small>Forma · ${row.recent?.n||0}</small></div><div class="pwp-trend ${t.cls}"><b>${t.label}</b><small>Última variación</small></div><div class="pwp-stability"><b>${stabilityLabel(row)}</b><small>${row.stability===null?'—':`σ ${row.stability.toFixed(2)} · ${row.series.length} notas`}</small></div><div class="pwp-spark-wrap">${spark(row)}</div><button class="pwp-radar" onclick="event.stopPropagation();RMPowerPro.radar('${row.p.name.replace(/'/g,"\\'")}')">Radar</button></article>`}
function render(){
  const section=document.getElementById('power');if(!section||!season()||typeof players==='undefined')return;const all=allRows(),powerRows=powerFiltered(),rows=visibleRows(),leader=powerRows[0]||null,second=powerRows[1]||null,bestForm=[...powerRows].filter(x=>x.recent?.n>=2).sort((a,b)=>b.recent.value-a.recent.value)[0]||null,stable=[...powerRows].filter(x=>x.stability!==null&&x.series.length>=3&&(x.m?.minutes||0)>=180).sort((a,b)=>a.stability-b.stability)[0]||null,gap=leader&&second?leader.power-second.power:null,cfg=sortConfig();
  section.innerHTML=`<div class="section-head"><div><div class="eyebrow">POWER RM PRO</div><h2>Power RM</h2><p>Rendimiento ajustado por muestra dentro de <b>${esc(contextLabel())}</b>. Cambiar el periodo recalcula el ranking, no solo oculta filas.</p></div><button class="btn" onclick="showSection('evolucion')">Ver evolución</button></div>${contextControls()}
  <div class="pwp-hero"><div class="pwp-leader"><span>LÍDER POWER DEL FILTRO</span><h2>${leader?esc(leader.p.short||leader.p.name):'—'}</h2><strong>${leader?leader.power.toFixed(2):'—'}</strong><small>${leader?`Media ${leader.r.toFixed(2)} · ${leader.m.minutes} min · ${Math.round(leader.sample*100)}% muestra`:'Sin jugadores con este filtro'}</small></div><div class="pwp-hero-grid"><div><span>Distancia al 2.º Power</span><b>${gap===null?'—':gap.toFixed(2)}</b><small>${closestText(powerRows)}</small></div><div><span>Mejor forma</span><b>${bestForm?esc(bestForm.p.short||bestForm.p.name):'—'}</b><small>${bestForm?`${bestForm.recent.value.toFixed(2)} · ${bestForm.recent.n} notas`:'Sin muestra suficiente'}</small></div><div><span>Más estable</span><b>${stable?esc(stable.p.short||stable.p.name):'—'}</b><small>${stable?`σ ${stable.stability.toFixed(2)} · ${stable.series.length} notas`:'Necesita 3 notas y 180 min'}</small></div></div></div>
  <div class="pwp-podium">${powerRows.slice(0,3).map(r=>`<button onclick="RMPowerPro.open('${r.p.name.replace(/'/g,"\\'")}')"><span>#${r.rank}</span><b>${esc(r.p.short||r.p.name)}</b><strong>${r.power.toFixed(2)}</strong><small>${sampleLabel(r)} · ${Math.round(r.sample*100)}%</small></button>`).join('')}</div>
  <div class="card pwp-controls"><div><span>POSICIÓN</span><div>${[['ALL','Todos'],['POR','POR'],['DEF','DEF'],['MED','MED'],['ATA','ATA']].map(([v,l])=>`<button class="${ppPos===v?'active':''}" onclick="RMPowerPro.position('${v}')">${l}</button>`).join('')}</div></div><div><span>MUESTRA MÍNIMA</span><select class="select" onchange="RMPowerPro.minimum(Number(this.value))"><option value="0" ${ppMin===0?'selected':''}>Todos</option><option value="90" ${ppMin===90?'selected':''}>90+ min</option><option value="180" ${ppMin===180?'selected':''}>180+ min</option><option value="270" ${ppMin===270?'selected':''}>270+ min</option></select></div><div><span>ORDENAR TABLA</span><select class="select" onchange="RMPowerPro.sort(this.value)"><option value="power" ${ppSort==='power'?'selected':''}>Power RM</option><option value="form" ${ppSort==='form'?'selected':''}>Forma · últimas 3 apariciones</option><option value="rating" ${ppSort==='rating'?'selected':''}>Media oficial</option><option value="minutes" ${ppSort==='minutes'?'selected':''}>Minutos jugados</option><option value="stability" ${ppSort==='stability'?'selected':''}>Estabilidad (σ)</option></select></div></div>
  <div class="card pwp-explain"><div><div class="eyebrow">CÓMO LEER POWER</div><h3>La muestra puede cambiar la interpretación, no la nota original</h3><p>Power RM = media × (0,75 + 0,25 × muestra). La muestra llega al 100% a los 450 minutos del contexto elegido. Un jugador con pocos minutos conserva su media, pero su Power se modera hasta que acumula evidencia.</p></div><div><b>${all.length}</b><span>jugadores con Power</span><small>SC conserva minutos de muestra, pero nunca se convierte en una nota 0 ni penaliza Min/punto.</small></div></div>
  <div class="pwp-list-head"><span>Jugador</span><span>${esc(cfg.head)}</span><span>Media</span><span>Min</span><span>Forma</span><span>Tendencia</span><span>Estabilidad</span><span>Curva</span><span></span></div><div class="pwp-list">${rows.length?rows.map(rowHtml).join(''):'<div class="pwp-empty">No hay jugadores que cumplan este filtro.</div>'}</div>
  <div class="pwp-integrity"><b>La tabla ahora sigue exactamente el criterio que eliges.</b><span>El número # y el valor grande de cada fila pertenecen a la clasificación seleccionada. Si ordenas por Forma, Media, Minutos o Estabilidad, Power queda como referencia secundaria. El podio y el bloque superior siguen siendo exclusivamente Power RM.</span></div>`;
  document.body.classList.add('power-pro-ready');
}
function openPlayer(name){if(window.RMPlayerExperience?.open)window.RMPlayerExperience.open(name);else if(typeof openPlayerHub==='function')openPlayerHub(name)}
function radar(name){const leader=allRows()[0]?.p.name;if(!leader||leader===name){if(typeof showSection==='function')showSection('radar');return}if(typeof showSection==='function')showSection('radar');setTimeout(()=>window.RMDecisionRadar?.set?.(name,leader),40)}
window.RMPowerPro=Object.freeze({render,open:openPlayer,radar,position:v=>{ppPos=v;render()},minimum:v=>{ppMin=Number(v)||0;render()},sort:v=>{ppSort=v;render()},rows:allRows,context});
['rm-power-official-ready','rm-ranking-official-ready','rm-season-data-ready','rm-analysis-context-updated'].forEach(name=>document.addEventListener(name,()=>setTimeout(render,0)));
setTimeout(render,0);
})();