(()=>{
let installed=false;
const SHARE_SECTIONS=new Set(['plantilla','comparador','once','prediccion']);
function go(id){if(typeof showSection==='function')showSection(id)}
function setText(el,text){if(el&&el.textContent!==text)el.textContent=text}
function setHtml(el,html){if(el&&el.innerHTML!==html)el.innerHTML=html}
function setPlaceholder(el,text){if(el&&el.placeholder!==text)el.placeholder=text}
function ensureMeta(name,content,property=false){let el=document.head.querySelector(`meta[${property?'property':'name'}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(property?'property':'name',name);document.head.appendChild(el)}if(el.getAttribute('content')!==content)el.setAttribute('content',content)}
function publicMeta(){const title='RM 26/27 · Datos, XI y comunidad del Real Madrid';if(document.title!==title)document.title=title;const description='Sigue el Real Madrid 2026/27 con rankings de rendimiento, Power RM, comparador de jugadores, constructor de XI y predicciones de la comunidad.';ensureMeta('description',description);ensureMeta('theme-color','#071421');ensureMeta('og:title','RM 26/27 · Datos, XI y comunidad',true);ensureMeta('og:description',description,true);ensureMeta('og:type','website',true)}
function updateHomeTopbar(id){if(id!=='inicio')return;setText(document.getElementById('pageTitle'),'Real Madrid 26/27');setText(document.getElementById('pageSub'),'Rendimiento, onces, comparaciones y comunidad en un solo lugar.')}
function injectIntro(){const home=document.getElementById('inicio');if(!home||document.getElementById('publicIntro'))return;const intro=document.createElement('section');intro.id='publicIntro';intro.className='card public-intro';intro.innerHTML=`<div class="public-copy"><div class="public-kicker">Real Madrid 26/27 · proyecto independiente</div><h2>Vive la temporada con datos, debate y tu propio XI.</h2><p>Compara jugadores, descubre quién llega mejor, construye alineaciones y compite acertando los titulares del próximo partido. Sin registro y con una metodología visible.</p><div class="public-actions"><button class="btn primary" id="publicPredict">Predecir el XI</button><button class="btn" id="publicPerformance">Ver quién está mejor</button></div><div class="public-trust"><span>3 fuentes de valoración</span><span>Sin corte mínimo de minutos</span><span>Sin registro</span><span>No oficial</span></div></div><div class="public-guide"><div class="public-guide-title">Empieza por aquí</div><button id="publicGuidePrediction"><i>11</i><span><b>Acierta el próximo XI</b><small>Elige tus titulares y compáralos con la comunidad.</small></span><strong>›</strong></button><button id="publicGuidePower"><i>⚡</i><span><b>¿Quién está rindiendo mejor?</b><small>Ranking, Power RM, forma y eficiencia.</small></span><strong>›</strong></button><button id="publicGuideCompare"><i>VS</i><span><b>Compara dos jugadores</b><small>Minutos, media, aporte y eficiencia cara a cara.</small></span><strong>›</strong></button></div>`;home.insertBefore(intro,home.firstChild);intro.querySelector('#publicPredict').onclick=()=>go('prediccion');intro.querySelector('#publicPerformance').onclick=()=>go('power');intro.querySelector('#publicGuidePrediction').onclick=()=>go('prediccion');intro.querySelector('#publicGuidePower').onclick=()=>go('power');intro.querySelector('#publicGuideCompare').onclick=()=>go('comparador')}
function improveCopy(){setText(document.querySelector('.brand small'),'Datos · XI · Comunidad');setHtml(document.querySelector('.side-bottom'),'<b style="color:#fff">Proyecto independiente</b><br>Análisis no oficial del Real Madrid 26/27.');setText(document.querySelector('#inicio .next-match .actions .btn:nth-child(2)'),'Ver nuestra predicción');const noteTitle=[...document.querySelectorAll('#inicio h2')].find(x=>x.textContent.trim()==='Bloc del proyecto'||x.textContent.trim()==='Mis notas');if(noteTitle){setText(noteTitle,'Mis notas');setText(noteTitle.parentElement?.querySelector('p'),'Guarda aquí tus ideas sobre onces, descansos o dudas tácticas. Solo se almacenan en este dispositivo.')}setText(document.querySelector('#plantilla .section-head p'),'Explora la plantilla, abre la ficha de cada jugador y consulta su rendimiento actual.');setText(document.querySelector('#comparador>.section-head p'),'Elige dos jugadores y mira quién sale por delante en rendimiento, forma, eficiencia y muestra.');setText(document.querySelector('#estadisticas>.section-head p'),'Explora la temporada por media, Power, forma, minutos, aporte, eficiencia y tamaño de muestra.');setText(document.querySelector('#partidos>.section-head p'),'Recorre cada jornada con notas, minutos, cobertura de fuentes y evolución respecto al partido anterior.');setText(document.querySelector('#evolucion>.section-head p'),'Sigue quién sube, quién cae, las rachas y los cambios de forma jornada a jornada.');setText(document.querySelector('#prediccion>.section-head p'),'Construye tu XI, compáralo con nuestra propuesta y guárdalo antes del cierre.');setText(document.querySelector('#once>.section-head p'),'Construye variantes válidas de 11 jugadores, compara con el once base y prueba alternativas por posición.');setText(document.querySelector('#uxHomeMore>summary b'),'Análisis avanzado, metodología y herramientas');const useIdea=[...document.querySelectorAll('#prediccion button')].find(b=>['Usar nuestra idea','Cargar propuesta'].includes(b.textContent.trim()));setText(useIdea,'Cargar propuesta');setPlaceholder(document.getElementById('lineupComment'),'Ej.: por qué jugaría este once, quién descansaría y qué cambios harías…');if(!document.getElementById('publicDisclaimer')){const home=document.getElementById('inicio');if(home){const d=document.createElement('p');d.id='publicDisclaimer';d.className='public-disclaimer';d.innerHTML='<b>RM 26/27</b> es un proyecto independiente y no oficial. Las valoraciones se combinan a partir de las fuentes indicadas en la metodología.';home.appendChild(d)}}}
function loadAccessibility(){if(!document.querySelector('link[data-accessibility]')){const link=document.createElement('link');link.rel='stylesheet';link.href='accessibility.css?v=1';link.dataset.accessibility='1';document.head.appendChild(link)}if(!document.querySelector('script[data-accessibility]')){const script=document.createElement('script');script.src='accessibility.js?v=1';script.dataset.accessibility='1';document.body.appendChild(script)}}
function loadCommandPalette(){if(!document.querySelector('link[data-command-palette]')){const link=document.createElement('link');link.rel='stylesheet';link.href='command-palette.css?v=1';link.dataset.commandPalette='1';document.head.appendChild(link)}if(!document.querySelector('script[data-command-palette]')){const script=document.createElement('script');script.src='command-palette.js?v=1';script.dataset.commandPalette='1';document.body.appendChild(script)}}
function loadEngagement(){if(!document.querySelector('link[data-public-engagement]')){const link=document.createElement('link');link.rel='stylesheet';link.href='public-engagement.css?v=3';link.dataset.publicEngagement='1';document.head.appendChild(link)}if(!document.querySelector('script[data-public-engagement]')){const script=document.createElement('script');script.src='public-engagement.js?v=3';script.dataset.publicEngagement='1';document.body.appendChild(script)}}
function loadGuide(){if(!document.querySelector('link[data-site-guide]')){const link=document.createElement('link');link.rel='stylesheet';link.href='site-guide.css?v=1';link.dataset.siteGuide='1';document.head.appendChild(link)}if(!document.querySelector('script[data-site-guide]')){const script=document.createElement('script');script.src='site-guide.js?v=1';script.dataset.siteGuide='1';document.body.appendChild(script)}}
function loadPersonalHome(){if(!document.querySelector('link[data-personal-home]')){const link=document.createElement('link');link.rel='stylesheet';link.href='personal-home.css?v=1';link.dataset.personalHome='1';document.head.appendChild(link)}if(!document.querySelector('script[data-personal-home]')){const script=document.createElement('script');script.src='personal-home.js?v=1';script.dataset.personalHome='1';document.body.appendChild(script)}}
function loadSquadPro(){if(!document.querySelector('link[data-squad-pro]')){const link=document.createElement('link');link.rel='stylesheet';link.href='squad-pro.css?v=1';link.dataset.squadPro='1';document.head.appendChild(link)}if(!document.querySelector('script[data-squad-pro]')){const script=document.createElement('script');script.src='squad-pro.js?v=1';script.dataset.squadPro='1';document.body.appendChild(script)}}
function loadComparePro(){if(!document.querySelector('link[data-compare-pro]')){const link=document.createElement('link');link.rel='stylesheet';link.href='compare-pro.css?v=1';link.dataset.comparePro='1';document.head.appendChild(link)}if(!document.querySelector('script[data-compare-pro]')){const script=document.createElement('script');script.src='compare-pro.js?v=1';script.dataset.comparePro='1';document.body.appendChild(script)}}
function loadStatsPro(){if(!document.querySelector('link[data-stats-pro]')){const link=document.createElement('link');link.rel='stylesheet';link.href='stats-pro.css?v=1';link.datasetStatsPro='1';link.dataset.statsPro='1';document.head.appendChild(link)}if(!document.querySelector('script[data-stats-pro]')){const script=document.createElement('script');script.src='stats-pro.js?v=1';script.dataset.statsPro='1';document.body.appendChild(script)}}
function loadMatchHistoryPro(){if(!document.querySelector('link[data-match-history-pro]')){const link=document.createElement('link');link.rel='stylesheet';link.href='match-history-pro.css?v=1';link.dataset.matchHistoryPro='1';document.head.appendChild(link)}if(!document.querySelector('script[data-match-history-pro]')){const script=document.createElement('script');script.src='match-history-pro.js?v=1';script.dataset.matchHistoryPro='1';document.body.appendChild(script)}}
function loadPredictionPro(){if(!document.querySelector('link[data-prediction-pro]')){const link=document.createElement('link');link.rel='stylesheet';link.href='prediction-pro.css?v=1';link.dataset.predictionPro='1';document.head.appendChild(link)}if(!document.querySelector('script[data-prediction-pro]')){const script=document.createElement('script');script.src='prediction-pro.js?v=1';script.dataset.predictionPro='1';document.body.appendChild(script)}}
function loadLineupPro(){if(!document.querySelector('link[data-lineup-pro]')){const link=document.createElement('link');link.rel='stylesheet';link.href='lineup-pro.css?v=1';link.dataset.lineupPro='1';document.head.appendChild(link)}if(!document.querySelector('script[data-lineup-pro]')){const script=document.createElement('script');script.src='lineup-pro.js?v=1';script.dataset.lineupPro='1';document.body.appendChild(script)}}
function loadEvolutionPro(){if(!document.querySelector('link[data-evolution-pro]')){const link=document.createElement('link');link.rel='stylesheet';link.href='evolution-pro.css?v=1';link.dataset.evolutionPro='1';document.head.appendChild(link)}if(!document.querySelector('script[data-evolution-pro]')){const script=document.createElement('script');script.src='evolution-pro.js?v=1';script.dataset.evolutionPro='1';document.body.appendChild(script)}}
function loadPowerPro(){if(!document.querySelector('link[data-power-pro]')){const link=document.createElement('link');link.rel='stylesheet';link.href='power-pro.css?v=1';link.dataset.powerPro='1';document.head.appendChild(link)}if(!document.querySelector('script[data-power-pro]')){const script=document.createElement('script');script.src='power-pro.js?v=1';script.dataset.powerPro='1';document.body.appendChild(script)}}
function loadShareCards(){if(!document.querySelector('link[data-share-cards]')){const link=document.createElement('link');link.rel='stylesheet';link.href='share-cards.css?v=2';link.dataset.shareCards='1';document.head.appendChild(link)}if(!document.querySelector('script[data-share-cards]')){const script=document.createElement('script');script.src='share-cards.js?v=2';script.dataset.shareCards='1';document.body.appendChild(script)}}
function refreshPublicCopy(){injectIntro();improveCopy();updateHomeTopbar(document.querySelector('.section.active')?.id||'inicio')}
function install(){
  if(installed)return;if(!document.getElementById('inicio')||typeof showSection!=='function'){setTimeout(install,80);return}
  installed=true;publicMeta();document.body.classList.add('public-ready');refreshPublicCopy();loadAccessibility();loadCommandPalette();loadEngagement();loadGuide();loadPersonalHome();
  const base=showSection;showSection=function(id){if(SHARE_SECTIONS.has(id))loadShareCards();if(id==='plantilla')loadSquadPro();if(id==='power')loadPowerPro();if(id==='comparador')loadComparePro();if(id==='estadisticas')loadStatsPro();if(id==='partidos')loadMatchHistoryPro();if(id==='prediccion')loadPredictionPro();if(id==='once')loadLineupPro();if(id==='evolucion')loadEvolutionPro();base(id);updateHomeTopbar(id);setTimeout(improveCopy,0);setTimeout(()=>{window.RMSquadPro?.render?.();window.RMPowerPro?.render?.();window.RMPredictionPro?.render?.();window.RMLineupPro?.render?.();window.RMEvolutionPro?.render?.();window.RMAccessibility?.refresh?.()},0)};
  const active=document.querySelector('.section.active')?.id;if(SHARE_SECTIONS.has(active))loadShareCards();if(active==='plantilla')loadSquadPro();if(active==='power')loadPowerPro();if(active==='comparador')loadComparePro();if(active==='estadisticas')loadStatsPro();if(active==='partidos')loadMatchHistoryPro();if(active==='prediccion')loadPredictionPro();if(active==='once')loadLineupPro();if(active==='evolucion')loadEvolutionPro();
  [300,1000].forEach(ms=>setTimeout(refreshPublicCopy,ms));document.addEventListener('rm-season-data-ready',()=>setTimeout(refreshPublicCopy,0),{once:true});
}
setTimeout(install,100);
})();