(()=>{
const SEEN_KEY='rm_site_guide_seen_v1';
let installed=false;
const GUIDE={
  inicio:{title:'La temporada de un vistazo',copy:'Aquí reunimos lo que más merece tu atención ahora: próximo partido, forma, rankings, comunidad y tus accesos personales.',look:['Empieza por “El pulso de la temporada” para ver qué está pasando ahora.','Si quieres participar, entra en Predicción y elige tu XI.','Si buscas rendimiento puro, Power y Comparador son los atajos más rápidos.'],action:['power','Ver quién está mejor']},
  partido:{title:'La previa del próximo partido',copy:'Esta pantalla concentra lo que puede cambiar el siguiente once: contexto, debates, nuestra idea y pulso de la comunidad.',look:['Mira primero qué jugadores consideramos fijos.','Después revisa los duelos abiertos por posición.','Nuestra propuesta es una previsión del proyecto, no una alineación oficial.'],action:['prediccion','Hacer mi predicción']},
  plantilla:{title:'Todos los jugadores, con contexto',copy:'No es solo una lista de nombres. Cada ficha reúne rendimiento, minutos, Power, forma reciente, posiciones y tus favoritos.',look:['La estrella ☆ guarda jugadores en favoritos solo en este dispositivo.','Toca una ficha para ver su evolución partido a partido.','Usa el buscador o filtra POR, DEF, MED y ATA para ir más rápido.'],action:['comparador','Comparar dos jugadores']},
  estadisticas:{title:'Los números base de la temporada',copy:'Esta es la tabla más directa para consultar media, minutos, aporte y eficiencia sin interpretación táctica adicional.',look:['Media te dice el rendimiento acumulado de las valoraciones publicadas.','Aporte mezcla nota y minutos: jugar bien durante más tiempo suma más.','Min/punto se lee al revés: cuanto menor, más aporte genera por minuto.'],action:['power','Ver Power RM']},
  power:{title:'Rendimiento + fiabilidad de muestra',copy:'Power RM intenta evitar que una nota enorme en pocos minutos pese igual que un rendimiento sostenido. Combina media y tamaño de muestra.',look:['La media sigue siendo el punto de partida.','La muestra gana peso progresivamente hasta 450 minutos.','Power no decide quién debe ser titular: es una señal de rendimiento actual.'],action:['comparador','Comparar jugadores']},
  eficiencia:{title:'Cuánto produce cada minuto',copy:'La eficiencia responde a una pregunta sencilla: ¿cuántos minutos necesita un jugador para generar un punto de aporte?',look:['Menor min/punto = mejor eficiencia.','Una muestra pequeña puede producir cifras llamativas, así que mira también minutos.','No sustituye a la media ni al Power: cuenta otra parte de la historia.'],action:['estadisticas','Ver tabla completa']},
  evolucion:{title:'Cómo cambia cada jugador con los partidos',copy:'Aquí puedes seguir las notas encuentro a encuentro para distinguir una tendencia de un partido aislado.',look:['Mira la secuencia, no solo el último número.','La forma reciente utiliza los últimos partidos con valoración disponible.','Los cambios tras una nueva jornada se recalculan cuando entran los datos oficiales del proyecto.'],action:['plantilla','Abrir fichas de jugadores']},
  jerarquias:{title:'Quién parte por delante ahora',copy:'La jerarquía es un modelo interno que cruza rendimiento, muestra, forma y nuestras decisiones. Sirve para ordenar debates, no para afirmar qué hará el entrenador.',look:['“Titular claro” significa ventaja fuerte en nuestro modelo.','“Duelo abierto” indica que la diferencia no es suficiente para cerrar la posición.','La jerarquía puede cambiar después de cada partido.'],action:['radar','Ver duelos clave']},
  radar:{title:'Decisiones cara a cara',copy:'El Radar compara dudas concretas por rondas: rendimiento, Power, minutos, eficiencia, forma y, cuando existe, comunidad.',look:['Ganar más rondas no convierte automáticamente a nadie en titular.','Cada criterio mide algo distinto y puede apuntar en otra dirección.','Úsalo para entender por qué un debate está abierto.'],action:['comparador','Abrir comparador']},
  comparador:{title:'Dos jugadores, la misma escala',copy:'El Comparador pone frente a frente las métricas principales para que puedas ver rápidamente dónde gana cada futbolista.',look:['Compara primero media y Power para rendimiento general.','Después mira minutos para saber cuánta muestra sostiene esos números.','Min/punto es mejor cuanto más bajo sea.'],action:['plantilla','Volver a la plantilla']},
  laboratorio:{title:'Un XI construido por los datos',copy:'El Laboratorio busca una alineación válida según el criterio que elijas. Es una herramienta de análisis, no nuestra predicción del próximo partido.',look:['Puedes priorizar equilibrio, Power, media, minutos o eficiencia.','Los filtros de muestra evitan que jugadores con muy pocos minutos dominen el resultado.','Después puedes llevar ese XI al constructor o a tu predicción.'],action:['once','Llevarlo al constructor']},
  once:{title:'Tu pizarra para probar ideas',copy:'El Constructor te deja montar un 4-2-3-1 adaptable, guardar escenarios y anotar por qué elegirías cada opción.',look:['Las posiciones disponibles respetan la elegibilidad definida en el proyecto.','Puedes guardar varios onces para comparar ideas.','Compartir XI crea una tarjeta visual cuando esa capa está cargada.'],action:['prediccion','Usarlo para predecir']},
  comunidad:{title:'Qué está eligiendo la gente',copy:'Aquí agregamos las predicciones publicadas para ver el XI más popular, porcentajes por posición y ranking de aciertos.',look:['El porcentaje de una posición indica cuántas predicciones colocan ahí a ese jugador.','El porcentaje global evita perder de vista a quienes aparecen en varias posiciones.','El ranking empieza a contar cuando existe un XI oficial contra el que puntuar.'],action:['prediccion','Publicar mi XI']},
  prediccion:{title:'Acierta los 11 titulares',copy:'Elige tu once para el próximo partido. Tu predicción se guarda en el dispositivo y, si publicas, también entra en la comunidad.',look:['Necesitas 11 jugadores distintos.','La predicción puede modificarse hasta la hora de cierre.','La puntuación cuenta titulares acertados, no la posición exacta en la que los colocaste.'],action:['comunidad','Ver qué piensa la comunidad']},
  mvp:{title:'El mejor del partido según la comunidad',copy:'La votación MVP sirve para recoger la percepción de la gente tras cada encuentro y compararla con los datos.',look:['Es opinión comunitaria, no una valoración estadística.','Puede diferir de SofaScore, FotMob, StatMuse o de nuestra media combinada.','Esa diferencia también es información útil.'],action:['evolucion','Ver notas del partido']},
  partidos:{title:'El archivo de la temporada',copy:'Aquí están los encuentros ya incorporados al seguimiento, para que sepas exactamente qué partidos alimentan rankings y tendencias.',look:['Solo los partidos integrados en el sistema afectan a las métricas.','Una nueva jornada entra cuando minutos y estados de las tres fuentes están cerrados.','SC significa “comprobado sin calificación”, no un cero.'],action:['evolucion','Ver evolución']},
  'mi-temporada':{title:'Tu historial personal',copy:'Esta zona recuerda tus predicciones y calcula tu media de aciertos, récords y logros. Todo vive en este dispositivo.',look:['No necesitas crear una cuenta.','Cada jornada puntuada añade tus aciertos al historial.','Tu nivel personal evoluciona a medida que acumulas predicciones.'],action:['prediccion','Hacer una predicción']}
};
const GLOSSARY=[
 ['Media','Rendimiento acumulado de las valoraciones oficiales del proyecto. Se calcula con las notas publicadas y queda ponderado por los minutos que tienen valoración.'],
 ['Power RM','Índice interno: media × (0,75 + 0,25 × muestra). La muestra aumenta con los minutos hasta un máximo de 450.'],
 ['Aporte','Nota oficial × minutos / 90. Combina calidad y tiempo jugado: una misma nota aporta más si se mantiene durante más minutos.'],
 ['Min/punto','Minutos totales jugados divididos por el aporte acumulado. Cuanto menor sea el número, mayor es la eficiencia por minuto.'],
 ['Muestra','Cantidad de minutos que sostiene una métrica. En Power, la muestra alcanza su peso máximo a los 450 minutos.'],
 ['3/3','Las tres fuentes —SofaScore, FotMob y StatMuse— publicaron valoración para esa aparición.'],
 ['SC','“Sin calificación”. La fuente fue comprobada y no publicó nota. No significa 0 y tampoco significa que el dato esté pendiente.'],
 ['Forma reciente','Media de hasta los tres últimos partidos del jugador que tienen una valoración oficial disponible.'],
 ['Jerarquía','Orden interno del proyecto para visualizar ventajas y duelos. No pretende adivinar automáticamente el once del entrenador.']
];
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function activeId(){return document.querySelector('.section.active')?.id||'inicio'}
function sectionName(id){try{return sections.find(s=>s[0]===id)?.[2]||id}catch{return id}}
function ensureButton(){
 const actions=document.querySelector('.topbar .actions');if(!actions||document.getElementById('siteGuideBtn'))return;
 const btn=document.createElement('button');btn.id='siteGuideBtn';btn.type='button';btn.className='btn site-guide-btn';btn.innerHTML='<span class="sg-icon">?</span><em>Guía</em>';btn.setAttribute('aria-label','Abrir guía de esta pantalla');btn.addEventListener('click',()=>openGuide());actions.prepend(btn);
}
function ensurePanel(){
 if(document.getElementById('siteGuide'))return;
 const root=document.createElement('div');root.id='siteGuide';root.className='site-guide';root.setAttribute('aria-hidden','true');root.innerHTML='<button class="site-guide-backdrop" type="button" aria-label="Cerrar guía"></button><aside class="site-guide-panel" role="dialog" aria-modal="true" aria-label="Guía de RM 26/27"><button class="site-guide-close" type="button" aria-label="Cerrar">×</button><div id="siteGuideContent"></div></aside>';
 document.body.appendChild(root);root.querySelector('.site-guide-backdrop').addEventListener('click',closeGuide);root.querySelector('.site-guide-close').addEventListener('click',closeGuide);
}
function fallbackGuide(id){return {title:sectionName(id),copy:'Esta pantalla forma parte del análisis RM 26/27. La guía se irá adaptando a las herramientas que estén disponibles.',look:['Mira primero el dato principal de la cabecera.','Usa los controles de la propia sección para profundizar.','Puedes volver a abrir esta guía cuando cambies de pantalla.'],action:['inicio','Volver al inicio']}}
function glossaryHtml(){return `<div class="sg-block"><span>DICCIONARIO RÁPIDO</span><div class="sg-glossary">${GLOSSARY.map(([term,def])=>`<div class="sg-term"><button type="button"><span>${esc(term)}</span><span>+</span></button><div class="sg-definition">${esc(def)}</div></div>`).join('')}</div></div>`}
function renderGuide(id=activeId()){
 const root=document.getElementById('siteGuideContent');if(!root)return;const g=GUIDE[id]||fallbackGuide(id);const actionExists=document.getElementById(g.action[0]);
 root.innerHTML=`<div class="sg-kicker">GUÍA · ${esc(sectionName(id).toUpperCase())}</div><h2 class="sg-title">${esc(g.title)}</h2><p class="sg-copy">${esc(g.copy)}</p><div class="sg-now"><span>EN 10 SEGUNDOS</span><b>${esc(g.look[0])}</b><small>${esc(g.look[1])}</small></div><div class="sg-block"><span>QUÉ MIRAR</span><div class="sg-points">${g.look.map((x,i)=>`<div class="sg-point"><i>${i+1}</i><div><b>${esc(x)}</b>${i===0?'<small>Empieza por aquí y profundiza solo si te interesa.</small>':''}</div></div>`).join('')}</div>${actionExists?`<button class="btn primary sg-action" type="button" data-sg-go="${esc(g.action[0])}">${esc(g.action[1])}</button>`:''}</div>${glossaryHtml()}`;
 root.querySelector('[data-sg-go]')?.addEventListener('click',e=>{const id=e.currentTarget.dataset.sgGo;closeGuide();if(typeof showSection==='function')showSection(id)});
 root.querySelectorAll('.sg-term button').forEach(btn=>btn.addEventListener('click',()=>{const term=btn.closest('.sg-term');const open=term.classList.toggle('open');btn.querySelector('span:last-child').textContent=open?'−':'+'}));
}
function openGuide(){ensurePanel();renderGuide();const root=document.getElementById('siteGuide');root.classList.add('open');root.setAttribute('aria-hidden','false');document.body.classList.add('site-guide-open');try{localStorage.setItem(SEEN_KEY,'1')}catch{};removeNudge()}
function closeGuide(){const root=document.getElementById('siteGuide');if(!root)return;root.classList.remove('open');root.setAttribute('aria-hidden','true');document.body.classList.remove('site-guide-open')}
function removeNudge(){document.getElementById('siteGuideNudge')?.remove()}
function maybeNudge(){
 let seen=false;try{seen=localStorage.getItem(SEEN_KEY)==='1'}catch{};if(seen||activeId()!=='inicio'||document.getElementById('siteGuideNudge'))return;
 const n=document.createElement('div');n.id='siteGuideNudge';n.className='sg-first-nudge';n.innerHTML='<div><b>¿Primera vez aquí?</b><small>Te explico cualquier pantalla y todas las métricas en lenguaje normal.</small></div><button type="button">Ver guía</button>';document.body.appendChild(n);n.querySelector('button').addEventListener('click',openGuide);setTimeout(()=>{if(document.getElementById('siteGuideNudge')===n)n.remove()},12000);
}
function install(){
 if(installed)return;if(typeof showSection!=='function'||!document.querySelector('.topbar .actions')){setTimeout(install,100);return}installed=true;ensureButton();ensurePanel();const base=showSection;showSection=function(id){base(id);closeGuide();removeNudge();setTimeout(ensureButton,0)};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeGuide();if(e.key==='?'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();openGuide()}});setTimeout(maybeNudge,1800);window.RMSiteGuide=Object.freeze({open:openGuide,close:closeGuide,render:renderGuide});
}
setTimeout(install,80);
})();
